### ISSUE TITLE
Support for multiple Graphites?

### ISSUE THREAD

**Issue by iiro** [sous-chefs/grafana#10]
Hi,

this is an enhancement question... Have you had any thoughts regarding for supporting multiple Graphite hosts...?

Sincerely,

Iiro Niinikoski

**Comment by JonathanTron** [comment]
Hi, I'm not against handling it in the grafana config file through attributes, anything beyond that is clearly out of scope and would be better served by a wrapper cookbook.

**Comment by iiro** [comment]
Ok. I will do a wrapper cookbook then - and I plan to use the the role search there... Thanks.
