### ISSUE TITLE
undefined method `datasource' for LWRP resource grafana_datasource from cookbook grafana

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#104]
using `chef 12.5.1` i've been running into the following issue:

```
grafana_datasource 'graphite-test' do
  datasource(
    type: 'graphite',
    url: 'http://10.0.0.15:8080',
    access: 'direct'
  )
end
```

error thrown is:

```
undefined method `datasource' for LWRP resource grafana_datasource from cookbook grafana
```

regards

**Comment by lanyonm** [comment]
Hey @gretel,
If you're using the most recent release you'll want to create a datasource with this syntax:

``` ruby
grafana_datasource 'graphite-test' do
  source(
    type: 'graphite',
    url: 'http://10.0.0.15:8080',
    access: 'direct'
  )
end
```

[reference](https://github.com/JonathanTron/chef-grafana/tree/v2.1.3)

If that's not the case, could you provide a bit more information on the context around the error?

**Comment by gretel** [comment]
i've been using the gem and just switched. me using berksehlf so i have
```
cookbook 'grafana', git: 'https://github.com/JonathanTron/chef-grafana.git'
```

in my Berksfile now. both versions seem to reference themselves as `2.1.3`.

**Comment by gretel** [comment]
i've been using the gem and just switched. me using berksehlf so i have

```
cookbook 'grafana', git: 'https://github.com/JonathanTron/chef-grafana.git'
```

in my Berksfile now. both versions seem to reference themselves as `2.1.3`.

**Comment by lanyonm** [comment]
You'll want that Berksfile line to look like this to pull the correct version:

``` ruby
cookbook 'grafana', git: 'https://github.com/JonathanTron/chef-grafana.git', tag: 'v2.1.3'
```

**Comment by gretel** [comment]
thanks, i'll track `HEAD` for now :)
