### ISSUE TITLE
grafana_user property isAdmin seems to have no effect

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#105]
```
grafana_user 'someone' do
  user(
    name: 'someone',
    email: 'user@host.org',
    password: 'haspass',
    isAdmin: true
  )
  action :create
end
```

user is being created, but does not get 'admin' permission.
additionally, i'd be great to have the other permissions (Viewer, Editor, Read Only Editor) reflected, too. using grafana 2.5.0. regards

**Comment by wfindley** [comment]
I'm also seeing this behavior using both grafana 2.1.3 and grafana 2.5.0.  I did not test older versions.

**Comment by gretel** [comment]
i'm going to try `isAdmin: 'true'` when i can.

**Comment by redterror** [comment]
I think this is a bug with the `:create` action.  If you first create the user, then call `grafana_user` again with the `:update` action, it applies correctly.

**Comment by gretel** [comment]
@redterror thanks!
@JonathanTron confirming workaround effective

**Comment by joshzitting** [comment]
This one should be closed with the latest changes..

**Comment by JonathanTron** [comment]
@gretel maybe you can confirm the latest commits from @joshzitting indeed fix the issue?

**Comment by gretel** [comment]
@JonathanTron will do on tuesday/cet. regards

**Comment by JonathanTron** [comment]
This merged PR https://github.com/JonathanTron/chef-grafana/pull/136 should have fixed it.
