### ISSUE TITLE
Need to add http_addr and auth.proxy config in grafana.ini

### ISSUE THREAD

**Issue by sputturao** [sous-chefs/grafana#107]
Couldn't find http_addr (under [server]) and auth.proxy attributes. Would appreciate if we can get the below attributes added:

['grafana']['ini']['server']['http_addr']
['grafana']['ini']['auth.proxy']['enabled']
['grafana']['ini']['auth.proxy']['header_name']
['grafana']['ini']['auth.proxy']['auto_sign_up']

**Comment by lanyonm** [comment]
Hey @sputturao,
You should be able to define all those attributes. In fact, you can see `http_addr` set in the kitchen tests here: https://github.com/JonathanTron/chef-grafana/blob/master/.kitchen.yml#L95.

Could you explain a bit further?

**Comment by sputturao** [comment]
Thanks for the quick response! let me test that out and get back to you.

**Comment by lanyonm** [comment]
Hey @sputturao,
I'm going to close this for now. Please let us know if you have questions or a suggestion for making this more clear in the documentation.

Thanks,
Mike
