### ISSUE TITLE
'isdefault: true' has no effect in context of 'grafana_datasource'

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#109]
the declaration of the resource

```
grafana_datasource 'graphite.ktchn' do
  datasource(
    type: 'graphite',
    url: 'http://10.0.200.10',
    access: 'proxy',
    isdefault: true,
  )
end
```

does not set this datasource as default.

**Comment by JonathanTron** [comment]
Hi @gretel,

the values given to `datasource` are serialized to json and sent as is to the Grafana `/api/datasources` endpoint, can you check the installed version of Grafana to ensure it has this option available?

**Comment by gretel** [comment]
@JonathanTron `grafana 2.5.0`. yes i did check, all the datasources defined are created, just none is set as default.

**Comment by lanyonm** [comment]
The Grafana docs have this parameter listed as `isDefault` (notice the capitalization). I'm not sure if that's the issue, but it certainly could be.

http://docs.grafana.org/reference/http_api/#update-an-existing-data-source

**Comment by redterror** [comment]
Using `isDefault` was required on my end to get it to set properly.

**Comment by gretel** [comment]
@JonathanTron confirming `isDefault` does work for us

**Comment by JonathanTron** [comment]
Great. Thanks for following up with the solution.
