### ISSUE TITLE
Endpoint not found when sending GET /api/dashboards/db/..

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#111]
declaring the resource

```
grafana_dashboard test do
  dashboard(
    source: 'dashboard_test',
  )
  action :create
end
```

results in a chef-run always failing and the dashboard not getting created:

```
         * grafana_dashboard[test] action update[2015-11-19T17:06:04+00:00] ERROR: Endpoint not found when sending GET /api/dashboards/db/test
       [2015-11-19T17:06:04+00:00] ERROR: Endpoint not found when sending POST /api/dashboards/db

           - Updating dashboard test
        (up to date)
```

i guess the logic is borked and always tried to update instead of create. regards

**Comment by JonathanTron** [comment]
Hi @gretel,

thanks for reporting the issue, can you tell more about the Grafana version installed? Is it correctly started?

**Comment by gretel** [comment]
@JonathanTron `grafana 2.5.0`. yes it gets started fine.

**Comment by moblidream** [comment]
Hi @gretel!
I have had the same issue before I fixed it by changing dashboard id to "null" instead of declared number inside dashboard json source file.

this:

``` bash
head -n 3 health.json
{ "dashboard": {
  "id": 17,
  "title": "health",
```

to this:

``` bash
head -n 3 health.json
{ "dashboard": {
  "id": null,
  "title": "health",
```

**Comment by obazoud** [comment]
Changing dashboard id to "null" works well for me too.

**Comment by rohit01** [comment]
Changing dashboard id to "null" works well for me too :-)

**Comment by JonathanTron** [comment]
This is something which was discussed previously, you can't create a new dashboard with an `id`, it has to be `null` or not specified. And we don't want to change the source of what you specify.
