### ISSUE TITLE
Release to Supermarket with LDAP Support

### ISSUE THREAD

**Issue by kemra102** [sous-chefs/grafana#112]
LDAP support has been in master for a while, any chance of a Supermarket release including it?

**Comment by lanyonm** [comment]
Hey @kemra102,
There are some questions about breaking changes in master that we need to sort out first, but I agree that a release is overdue. I might be able to have a look at that over the break and cherry-pick apart non-breaking changes.

**Comment by JonathanTron** [comment]
Yes, I think we'll do a new release with the breaking changes thus making it a 3.x version.

**Comment by predominant** [comment]
Any chance of this happening soon @lanyonm / @JonathanTron ?

**Comment by damacus** [comment]
This has been released now. 

Thanks!
