### ISSUE TITLE
Datasource Resource: In recent Grafana versions (2.6.0) "influxdb_09" is only called "influxdb"

### ISSUE THREAD

**Issue by chidniu** [sous-chefs/grafana#124]
Hi,

in the recent Grafana version the POST parameter to create an InfluxDB 0.9.x datasource is

```
"type": "influxdb"
```

which has to be used when creating it via this cookbook. A short mention of this in the README could potentially save people a lot of time.

**Comment by JonathanTron** [comment]
Hi @phoenixyz,

thanks for reporting this, I'll add it in the README as you've suggested.
