### ISSUE TITLE
org LWRP not working

### ISSUE THREAD

**Issue by joshzitting** [sous-chefs/grafana#126]
I am trying to loop thru some machines, Grab the env and create some organizations from that list (I will be using org as a type of location devider for now) 

`servers = search(:node, "tags:graphite")
servers.each do |g|
  grafana_organization "#{g.environment}" do
    action :create
  end
end`

Have also tried 
`servers = search(:node, "tags:graphite")
servers.each do |g|
  grafana_organization "#{g.environment}" do
    action :create
    name g.environment
  end
end`

It creates the first one then says it is up to date on the rest.. 

`* grafana_organization[testing] action create (up to date)
        (up to date)
        (up to date)
        (up to date)
        (up to date)`

I am using the latest (git) version of the cookbook.. the version on supermarket is old.. this needs a dev branch or something!

**Comment by joshzitting** [comment]
I just updated this ticket.. Any help is appreciated!

**Comment by hulu1522** [comment]
To make his code more readable:

``` ruby
# Get a list of servers
servers = search(:node, "tags:graphite")

# Loop over servers and create organizations
# based on their environment.
servers.each do |g|

  grafana_organization g.environment do
    action :create
    name g.environment
  end

end
```

Based on the code I believe it has something to do with the way this cookbook is using the API with a session instead of using oAuth in the command.  I may be wrong though.

**Comment by JonathanTron** [comment]
Hi @joshzitting and @hulu1522,

can you please tell us more about your setup? Chef version and the cookbook version you're using.

**Comment by joshzitting** [comment]
This testing is on a Kitchen run. Chef: 12.7.2 with Ubuntu 14.04 and the cookbook version that I was using was grafana (2.1.3) from the community but I have changed to pull it directly from this git repo because it has some newer features.. Same version though.

**Comment by hulu1522** [comment]
I think what may need to happen is that only one session ID should be generated (and set as a variable) that can be used during the whole cookbook run.  A 'default' attribute will be reset every run and you only have to 'login' once during a run.

**Comment by joshzitting** [comment]
@JonathanTron I have played with this and I have found a workaround... 
If you are going to be creating more than one org you need to pass in the organization['name'] feild or else providers/organization.rb: 
`unless new_resource.organization.key?(:name)`<br />`
    new_resource.organization[:name] = new_resource.name`<br />`
  end`
will constantly set new_resource.organization[:name] to the first one defined by LWRP 

EX do it this way.. (I might make a PR on some of the readme later too.. )

`````` ruby
servers = search(:node, "tags:graphite")
#Loop over servers and create organizations
#based on their environment.
servers.each do |g|
  grafana_organization g.environment do
    action :create
    organization(
    name: g.environment
)
 #name g.environment This way will not work!!! 
 end
end```
``````
