### ISSUE TITLE
add users to organization as part of the User LWRP

### ISSUE THREAD

**Issue by joshzitting** [sous-chefs/grafana#128]
right now the users can be created and admin works etc but there is not a way to add them to organizations.. Would ppl prefer to use the current user LWRP and pass in an array of orgs, or have a org_user LWRP that will create the user if it doesnt exist and then add the user to the org?? 
Im hoping to knock this out next week so throw in your 2¢ asap..

**Comment by JonathanTron** [comment]
It's now merged in master.
