### ISSUE TITLE
packagecloud yum doesn't work

### ISSUE THREAD

**Issue by jblaine** [sous-chefs/grafana#139]
At the bottom of this post is the configuration that the packagecloud "install" script creates in `/etc/yum.repos.d/grafana_stable.repo` on my RHEL7 box. It works. The current `_install_package.rb` recipe does not and instead results in:

```
https://packagecloud.io/grafana/stable/el/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

The only real difference I can see is the GPG key location (the grafana cookbook currently defines it as 'https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana') and `gpgcheck` being set to 0.

```
[grafana_stable]
name=grafana_stable
baseurl=https://packagecloud.io/grafana/stable/el/7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/grafana/stable/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[grafana_stable-source]
name=grafana_stable-source
baseurl=https://packagecloud.io/grafana/stable/el/7/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/grafana/stable/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by jblaine** [comment]
Also note the `7Server` being filled in for `$releasever` in the 404 error, where the packagecloud-generated file just says `7`

**Comment by jblaine** [comment]
This worked FWIW:

```
# Remove packagecloud-installed repo file
% sudo rm /etc/yum.repos.d/grafa*
```

And then in my wrapper recipe:

```
default['grafana']['package']['repo'] = 'https://packagecloud.io/grafana/stable/el/7/$basearch'
default['grafana']['package']['key'] = 'https://packagecloud.io/grafana/stable/gpgkey'
```

**Comment by JonathanTron** [comment]
Hi @jblaine, thanks for reporting it! 

The default attributes for the key url needs an update. Would you like to send a PR for it?

As for the `7Server` it seems to come from the usage of `$releasever` in the repo url, which should be replaced by the `package's version` (based on what I can read in the yum doc). 
Why would it be `7Server` on your machine I have no idea, I usually don't use `yum`/`rpm`. If you have more experience with it. Maybe we need to use a more _hardcoded_ (as in handle more case in the `attributes`) to not rely on `$releasever` variable if it proves to be unreliable to define the appropriate url for the repo.

**Comment by jblaine** [comment]
Hi Jonathan,

From the official RH docs:

```
$releasever

    You can use this variable to reference the release version of Red Hat Enterprise
    Linux. Yum obtains the value of $releasever from the distroverpkg=value line in
    the /etc/yum.conf configuration file. If there is no such line in /etc/yum.conf, then
    yum infers the correct value by deriving the version number from the redhat-release
    package. The value of $releasever typically consists of the major release number
    and the variant of Red Hat Enterprise Linux, for example 6Client, or 6Server. 
```

It's not clear yet really who is behaving "incorrectly", packagecloud.io or the attribute in this cookbook.

**Comment by scopenco** [comment]
Outdated issue. Closing.
