### ISSUE TITLE
Cannot install packages from an unsigned local repository

### ISSUE THREAD

**Issue by jhenry82** [sous-chefs/grafana#145]
I'm trying to install Grafana from a local yum repo which happens to not have a valid GPG signing key. I realize this is not a great practice, but it's an unfortunate reality of my current environment. The install fails because there's no way to disable GPG checking in the cookbook.

I've patched this locally to allow you to disable key checking (off by default, of course). Will send a pull request shortly.

**Comment by JonathanTron** [comment]
Pull request has been merged, I'm closing this issue.

Thanks for the work @jhenry82 !
