### ISSUE TITLE
Cannot install via chef solo in vagrant provision

### ISSUE THREAD

**Issue by pauldambra** [sous-chefs/grafana#147]
Apologies if this is the wrong place to raise this issue. I've created a vagrantfile using Berkshelf and chef solo in an attempt to setup grafana and receive the error 

```
==> default: undefined method `[]' for nil:NilClass
==> default:
==> default:
==> default: Cookbook Trace:
==> default:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'
==> default:   /var/chef/cache/cookbooks/nginx/recipes/default.rb:21:in `from_file'
==> default:   /var/chef/cache/cookbooks/grafana/recipes/_nginx.rb:20:in `from_file'
==> default:   /var/chef/cache/cookbooks/grafana/recipes/default.rb:21:in `from_file'
```

you can see more here https://github.com/pauldambra/loggererer

I've tried switching the box definition to ubuntu/precise64 and following the advice here https://github.com/JonathanTron/chef-grafana/issues/33 with no success. 

I imagine that this is a result of my lack of understanding and wondered if someone could point me in the right direction. Thanks in advance

**Comment by pauldambra** [comment]
Have just realised I didn't add the context that this was on Mac OSX latest.

**Comment by pauldambra** [comment]
I've vendored the packages locally (i.e. `berks vendor`) and pointed to them so my berksfile now looks like

```
source "https://supermarket.chef.io"

cookbook 'timezone'
cookbook 'graphite'
cookbook 'grafana', path: 'berks-cookbooks/grafana'
cookbook 'ohai', path: 'berks-cookbooks/ohai'
cookbook 'nginx', path: 'berks-cookbooks/nginx'
cookbook 'statsd'
```

I see the error in the first line of 

```
template "#{node['ohai']['plugin_path']}/nginx.rb" do
  source "plugins/nginx.rb.erb"
  owner "root"
  group "root"
  mode 00755
  variables(
    :nginx_prefix => node['nginx']['source']['prefix'],
    :nginx_bin => node['nginx']['binary']
  )
  notifies :reload, 'ohai[reload_nginx]', :immediately
end
```

and if I `puts node['ohai']` here there's no output whereas if I `puts node` there's _lots_

I'm not really sure how I go about checking if the problem is in the nginx cookbook or how it's used here.

**Comment by pauldambra** [comment]
Ah! Ohai has changed at v4. Locking nginx to v3.0.1 seems to fix it

**Comment by pauldambra** [comment]
Yep, and when my dependencies are sorted by berks I get nginx v 1.8.0 when 2.7.6 is the latest. well, at least I've learned a lot about investigating chef problems :)

**Comment by kirthar** [comment]
Hi @pauldambra . I found my self with the same issue, but I'm a bit noob on this. 
How did you lock nginx to v3.0.1 ?  

Thanks

EDIT: Oh! I saw it on your project code. Thanks !!
