### ISSUE TITLE
Fedora package version should not have "-1" appended.

### ISSUE THREAD

**Issue by reid-harrison** [sous-chefs/grafana#152]
https://github.com/JonathanTron/chef-grafana/blob/1eaedd8d8cdc825d981a2c903e2d82e688632ea2/attributes/default.rb#L38

I don't really understand why hard-coding a "-1" into the version is necessary since it just restricts the ability to properly override the attribute.

I would be happy to contribute the change if this issue is deemed appropriate.

**Comment by JonathanTron** [comment]
Hi @reid-harrison, thanks for taking the time to open the issue.

If it bother you and you can fix it, then I will be happy to merge your changes.

**Comment by t2y** [comment]
@JonathanTron I sent PR: #159

**Comment by scopenco** [comment]
Fixed in versions before 2.2.0.
