### ISSUE TITLE
Remove nginx dependency completely

### ISSUE THREAD

**Issue by JonathanTron** [sous-chefs/grafana#158]
In https://github.com/JonathanTron/chef-grafana/issues/148, the question about focusing on installation and configuration of Grafana, and remove the dependency on nginx has been raised.

This issue is meant to continue the discussion and reference actions to be taken if we decide to go this route.

**Comment by scopenco** [comment]
I agree that nginx should be removed from this cookbook. Grafana cookbook should configure grafana only.

**Comment by xorima** [comment]
This will be done in the 4.0.0 release
