### ISSUE TITLE
nginx prevents dependecies from resolving

### ISSUE THREAD

**Issue by marcpawl** [sous-chefs/grafana#161]
nginx prevents dependecies from resolving, failing on apt

See  Remove nginx dependency completely #158 

knife cookbook site install grafana  --config /root/.chef/knife.rb
RUN knife solve  grafana --config /root/.chef/knife.rb  ;   knife solve  nginx --config /root/.chef/knife.rb  ;   knife solve  apt --config /root/.chef/knife.rb
 ---> Running in fc89212832e1
Solving [grafana] in _default environment
ERROR: Precondition Failed
Response: Could not satisfy version constraints for: apt
olving [nginx] in _default environment
RROR: Precondition Failed
Response: Could not satisfy version constraints for: apt
Solving [apt] in _default environment
apt 5.1.0

Downgrading to old versions fails on nginx
knife cookbook site install apt 2.2.1  --config /root/.chef/knife.rb
knife cookbook site install bluepill 2.3.1  --config /root/.chef/knife.rb
knife cookbook site install build-essential 2.0.6 --skip-dependencies --config /root/.chef/knife.rb
knife cookbook site install ohai 2.0.4 --skip-dependencies --config /root/.chef/knife.rb
knife cookbook site install runit 1.2.0 --skip-dependencies --config /root/.chef/knife.rb
knife cookbook site install yum-epel 0.3.6 --skip-dependencies --config /root/.chef/knife.rb
knife cookbook site install yum 3.0.6 --skip-dependencies --config /root/.chef/knife.rb
knife solve  grafana --config /root/.chef/knife.rb ;   knife deps cookbooks/grafana --tree --config /root/.chef/knife.rb
 ---> Running in 2a6c6d064461
^[[91mSolving [grafana] in _default environment
^[[0mapt 2.2.1
bluepill 2.3.1
build-essential 2.0.6
compat_resource 12.16.3
grafana 2.1.3
nginx 2.7.6
ohai 2.0.4
rsyslog 5.1.0
runit 1.2.0
yum 3.0.6
yum-epel 0.3.6
cookbooks/grafana
  cookbooks/apt
  cookbooks/yum
  cookbooks/nginx
    cookbooks/apt
    cookbooks/bluepill
      cookbooks/rsyslog
        cookbooks/compat_resource
    cookbooks/build-essential
    cookbooks/ohai
    cookbooks/runit
      cookbooks/build-essential
      cookbooks/yum
    cookbooks/yum-epel
knife solve  grafana --config /root/.chef/knife.rb ;   knife deps cookbooks/grafana --tree --config /root/.chef/knife.rb
 ---> Running in 2a6c6d064461
^[[91mSolving [grafana] in _default environment
^[[0mapt 2.2.1
bluepill 2.3.1
build-essential 2.0.6
compat_resource 12.16.3
grafana 2.1.3
nginx 2.7.6
ohai 2.0.4
rsyslog 5.1.0
runit 1.2.0
yum 3.0.6
yum-epel 0.3.6
cookbooks/grafana
  cookbooks/apt
  cookbooks/yum
  cookbooks/nginx
    cookbooks/apt
    cookbooks/bluepill
      cookbooks/rsyslog
        cookbooks/compat_resource
    cookbooks/build-essential
    cookbooks/ohai
    cookbooks/runit
      cookbooks/build-essential
      cookbooks/yum
    cookbooks/yum-epel
      cookbooks/yum

 chef-solo -j grafanasetup.json --config /root/.chef/config.rb

[[0mChef::Exceptions::Service^[[0m
-------------------------^[[0m
service[nginx]: Service is not known to chkconfig.^[[0m

^[[0mResource Declaration:^[[0m
---------------------^[[0m
# In /root/.chef/local-mode-cache/cache/cookbooks/nginx/recipes/package.rb
^[[0m
^[[0m 47: service 'nginx' do
^[[0m 48:   supports :status => true, :restart => true, :reload => true
^[[0m 49:   action   :enable
^[[0m 50: end
^[[0m 51:
^[[0m

Execute the command
docker build .
to verify the test case.

[grafanasetup.zip](https://github.com/JonathanTron/chef-grafana/files/761484/grafanasetup.zip)

**Comment by kalebwalton** [comment]
It appears the 2.1.3 version committed to Supermarket still has the 'nginx' dependency instead of 'chef_nginx'. I did the following in my Berksfile and it worked:

cookbook 'grafana', "~> 2.1.3", git: "https://github.com/JonathanTron/chef-grafana"

**Comment by kpmueller** [comment]
Also seeing this issue

**Comment by scopenco** [comment]
Fixed in v2.2.0.
