### ISSUE TITLE
Multi ldap tree & servers

### ISSUE THREAD

**Issue by jfwm2** [sous-chefs/grafana#162]
Hello

It does not seem to me (at first glance) that there is a way to specify multiple [[servers]] sections ( see https://github.com/grafana/grafana/issues/3474).
If it is the case, we could start working on a PR for that. Any advice would be extremely welcome.

Best regards
JFWM

**Comment by xorima** [comment]
Hi, 
This is in the new 2.0.0 release, which should get out very soon
Sorry it's taken so long
