### ISSUE TITLE
Outdated cookbook version in supermarket.

### ISSUE THREAD

**Issue by Nklya** [sous-chefs/grafana#166]
Hello.

I faced problem with this cookbook.
In chef supermarket loaded very old version and with the same version, like on github - 2.1.3.
https://supermarket.chef.io/cookbooks/grafana

Could you please update cookbook in supermarket or at least bump version in metadata on github?

**Comment by josephholsten** [comment]
@Nklya we've got a new maintainer and are working to put out a release very soon!

**Comment by Nklya** [comment]
That would be great. Thank you.

**Comment by scopenco** [comment]
v2.2.0 has been released.
