### ISSUE TITLE
Cannot able to configure datasource using "grafana_datasource" resource.

### ISSUE THREAD

**Issue by BalasekharNelli12** [sous-chefs/grafana#167]
Hi @JonathanTron ,

We are facing  the issue in creating a datasource using the "grafana_datasoure" resource.

Getting the below error:

> Recipe: myprometheus::setup
>          * grafana_datasource[graphite-test] action create
>            
>            ================================================================================
>            Error executing action `create` on resource 'grafana_datasource[graphite-test]'
>            ================================================================================
>            
>            ArgumentError
>            -------------
>            Malformed version number string latest
>            
>            Cookbook Trace:
>            ---------------
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:65:in `legacy_http_semantic'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:58:in `block in do_create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:57:in `do_create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:40:in `create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:12:in `block in class_from_file'
>            
>            Resource Declaration:
>            ---------------------
>            # In /tmp/kitchen/cache/cookbooks/myprometheus/recipes/setup.rb
>            
>              3: grafana_datasource 'graphite-test' do
>              4:   source(
>              5:     type: 'graphite',
>              6:     url: 'http://10.0.0.15:8080',
>              7:     access: 'direct'
>              8:   )
>              9: end
>             10: 
>            
>            Compiled Resource:
>            ------------------
>            # Declared in /tmp/kitchen/cache/cookbooks/myprometheus/recipes/setup.rb:3:in `from_file'
>            
>            grafana_datasource("graphite-test") do
>              action [:create]
>              default_guard_interpreter :default
>              declared_type :grafana_datasource
>              cookbook_name "myprometheus"
>              recipe_name "setup"
>              source {:type=>"graphite", :url=>"http://10.0.0.15:8080", :access=>"direct", :name=>"graphite-test"}
>              source_name "graphite-test"
>            end
>            
>            System Info:
>            ------------
>            chef_version=13.2.20
>            platform=ubuntu
>            platform_version=14.04
>            ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
>            program_name=chef-solo worker: ppid=7240;start=10:48:55;
>            executable=/opt/chef/bin/chef-solo
> 

Thanks,
Bala

**Comment by elocnatsirt** [comment]
Manually set the Grafana version:

node.default['grafana']['version'] = '4.4.1'

**Comment by BalasekharNelli12** [comment]
I am still facing the issue.

Can you tell me how to add a dataresource?

>  Recipe: myprometheus::setup
>          * grafana_datasource[Prometheus] action create
>            
>            ================================================================================
>            Error executing action `create` on resource 'grafana_datasource[Prometheus]'
>            ================================================================================
>            
>            ArgumentError
>            -------------
>            Malformed version number string latest
>            
>            Cookbook Trace:
>            ---------------
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:65:in `legacy_http_semantic'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:58:in `block in do_create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:57:in `do_create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:40:in `create'
>            /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:12:in `block in class_from_file'
>            
>            Resource Declaration:
>            ---------------------
>            # In /tmp/kitchen/cache/cookbooks/myprometheus/recipes/setup.rb
>            
>             11: grafana_datasource 'Prometheus' do
>             12:   source(
>             13:     type: 'Prometheus',
>             14:     url: '10.132.166.11:9090',
>             15:     access: 'direct'
>             16:   )
>             17: end

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
