### ISSUE TITLE
Is somebody support this cookbook?

### ISSUE THREAD

**Issue by scopenco** [sous-chefs/grafana#174]

**Comment by josephholsten** [comment]
While I don't have the time to become a maintainer, I'd absolutely love to see this cookbook continue being awesome. If @JonathanTron would like some help, a bunch of cookbook maintainers are working together at @sous-chefs to join forces. The only requirement for a cookbook to join sous-chefs is to have someone willing to volunteer as primary maintainer. Once we have a volunteer, then we can follow http://sous-chefs.org/transferring/

**Comment by scopenco** [comment]
I'm ready to be a volunteer for this cookbook. In addition, i have several cookbooks and I can migrate some of them to @sous-chefs.

**Comment by josephholsten** [comment]
@JonathanTron are you interested in transferring the cookbook to sous-chefs? I've set up a PR to add you as a member: https://github.com/sous-chefs/terraform-github-org/pull/65, once that's in you'll have creds to transfer.

If you aren't interesting in moving to sous-chefs, that's still okay! I just want to make sure this cookbook has enough maintainers to keep it functional and healthy.

**Comment by jblaine** [comment]
Sorry to "me too!" this, but yeah - this is a bummer to see such a good cookbook that people like go on neglected like this.

**Comment by josephholsten** [comment]
@scopenco I've created a fork over at https://github.com/sous-chefs/chef-grafana, and you should have an invite to contribute to it. This is mostly intended as a workspace until we can get everyone on the same page. If you can make any progress on the open PRs and Issues here, I think everyone would benefit.

@JonathanTron If we don't hear anything from you before 2017-11-03, I'm going to move forward with http://sous-chefs.org/forking/. But I'd really like to keep the community together! Please let me know what you'd like to do.

**Comment by scopenco** [comment]
@josephholsten cool, thanks. I'll request PRs' Authors to move PRs to https://github.com/sous-chefs/chef-grafana so I can review it and proceed.

**Comment by JonathanTron** [comment]
Sorry for the late response, I've indeed had less time to work on this cookbook as of late.

I would gladly accept a transfer to sous-chefs if someone offers to maintain it there.

**Comment by scopenco** [comment]
@JonathanTron. I've started to update https://github.com/sous-chefs/chef-grafana, let's move development there. I'm ready to maintain this cookbook in `sous-chefs` org.

**Comment by josephholsten** [comment]
I wonder if it would be best to actually move the repo over to sous-chefs so people who end up here will be forwarded there! Also, then we don't lose the existing issues and PRs. @sous-chefs usually names the repos with the bare cookbook name, so maybe @JonathanTron could transfer to https://github.com/sous-chefs/grafana?

**Comment by josephholsten** [comment]
Oh, and I forgot we'll also need https://supermarket.chef.io/cookbooks/grafana transfered so we can make releases! My terrible memory is why we wrote http://sous-chefs.org/transferring/

@JonathanTron anything I can do to help you go through the process?

**Comment by JonathanTron** [comment]
@josephholsten Thanks for working out the PR and pushing me to move it. But as there is now already a chef-grafana in the sous-chefs org, I can't move mine there anymore (there's no way to rename the repo you want to transfer). I suppose I should rename it first, then try to transfer it again or we simply delete the existing `sous-chefs/chef-grafana` fork and I'll then transfer mine... 

What do you prefer?


/cc @scopenco

**Comment by JonathanTron** [comment]
@josephholsten I've also requested the transfer to sous-chefs in Supermarket.

**Comment by josephholsten** [comment]
@JonathanTron ah! Sorry about that, I've renamed the fork, you should be able to transfer now. I'll get one of the board to accept the supermarket transfer.

**Comment by JonathanTron** [comment]
@josephholsten No worries, we'll find a way to make it work. Unfortunately Github doesn't allow to transfer a repo to an org which already includes a fork of it, here's the message I receive:

```
sous-chefs already has a repository in the JonathanTron/chef-grafana network and You don’t have the permission to create repositories on sous-chefs
```

**Comment by josephholsten** [comment]
Well, I fixed the second error. Not sure what happened with our authorization repo, we'll have to post-mortem that, it's not fun for new people :-/

I've made sure I have all the commits @scopenco has added to our fork locally, and deleted our repo. You should be unblocked now?

**Comment by JonathanTron** [comment]
@josephholsten Thanks for your help moving this forward :)

**Comment by josephholsten** [comment]
Looks like we can close this!
