### ISSUE TITLE
_apache recipe is missed

### ISSUE THREAD

**Issue by osigida** [sous-chefs/grafana#19]
Hi,

I'm trying to set up grafana on apache and 
so I've set 
`node.default['grafana']['webserver'] = 'apache'`

but when I execute the recipe I get follow error
`could not find recipe _apache for cookbook grafana`

do I do something wrong?

**Comment by JonathanTron** [comment]
Hi, there is indeed no support for Apache in this cookbook, the attributes documentation is wrong. 

This cookbook is meant to be used as a by a wrapper cookbook. If you want to use Apache, simply set  `node.override['grafana']['webserver'] = ''` in your wrapper cookbook and add your logic to install/configure Apache.

Thanks for reporting it, I will change it.
