### ISSUE TITLE
"Endpoint not found" error log messages when (successfully) importing dashboards

### ISSUE THREAD

**Issue by salatamartin** [sous-chefs/grafana#194]
When importing dashboards to Grafana (even if the import is eventually successful), there is a check whether the dashboard already exists. This, however, produces an error message "ERROR: Endpoint not found when sending GET /api/dashboards/db/...". 

I think it would be better if the message wasn't shown as ERROR, because it makes the logs look a little confusing when parsing for further analysis.

I am using the grafana cookbook version 2.2.1 and this happens inside the grafana_dashboard resource.

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks

**Comment by salatamartin** [comment]
Hello,

the code responsible for this behavior didn't change: Create action on `dashboard` resource calls `get_dashboard` to make sure it doesn't already exist before creating. `get_dashboard` calls `do_request` which logs an ERROR message when 404 is returned, which is the correct (documented) behavior of Grafana API.

This means you always get an error log when first importing a dashboard. I don't think error messages should be logged if there isn't actually an error.

Thanks for considering my note, Martin

**Comment by axelrtgs** [comment]
I can confirm this is still an issue in the latest release.

**Comment by xorima** [comment]
Can you create a PR with tests we can focus on fixing for this please?

**Comment by bmhughes** [comment]
All deprecated API functionality will be removed with v10 with the recommendation of transitioning to a better suited tool such as Terraform for managing API resources, so this won't be getting fixed.
