### ISSUE TITLE
Version defaulted even though set

### ISSUE THREAD

**Issue by mcaulifn** [sous-chefs/grafana#199]
### Cookbook version
3.0.0

### Chef-client version
14.3.37

### Platform Details
Centos 7
Ubuntu 16.04

### Scenario:
Set Grafana version to install

### Steps to Reproduce:
1. In attributes/default.rb: default['grafana']['version'] = '5.2.0'
2. in recipes/default.rb: include_recipe 'grafana::default'
3. run kitchen converge

### Expected Result:
Grafana 5.2.0 to be installed

### Actual Result:
Grafana 4.6.3 is installed

Output the following variables using echo:
```
node['platform_family']
         * execute[platform] action run
           - execute echo rhel

node['grafana']['version']
         * execute[version] action run
           - execute echo 5.2.0

node['grafana']['package']['version']
         * execute[packageVersion] action run
           - execute echo 4.6.3-1
```

**Comment by eheydrick** [comment]
Hi @mcaulifn, are you still experiencing this issue? If so can you paste in the output from test-kitchen. I tried reproducing it and was unable to although I noticed you aren't setting the checksum for the package files. You'll want to set that otherwise you'll get a `ChecksumMismatch`.

All that's needed In `attributes/default.rb` for a newer version:
```
default['grafana']['version'] = '5.3.2'
default['grafana']['file']['checksum']['deb'] = 'e8d2369b3c541f181dd0d97d13704682161b4b831c3c0f0af08f8efbeb531a57'
default['grafana']['file']['checksum']['rpm'] = 'd70f46120fae84b784a3857a677e8f26cf48a74b97b1a2c0c43de5c64f6158f7'
```

**Comment by mcaulifn** [comment]
@eheydrick yes, this was still happening. I ended up hacking together my own recipe to get it to work. I switched back to using this one after your comment and it is still broken. I neglected to mention in the original post that I was using the package method.

```
default['grafana']['install_type'] = 'package'
default['grafana']['version'] = '5.2.4'
```

**Comment by mcaulifn** [comment]
<details><summary>kitchen converge</summary>

```
Recipe: grafana::_install_package
         * yum_repository[grafana] action create
           * template[/etc/yum.repos.d/grafana.repo] action create
             - create new file /etc/yum.repos.d/grafana.repo
             - update content in file /etc/yum.repos.d/grafana.repo from none to 123dd2
             --- /etc/yum.repos.d/grafana.repo	2018-10-25 12:30:27.386500170 +0000
             +++ /etc/yum.repos.d/.chef-grafana20181025-3237-1dnn1x4.repo	2018-10-25 12:30:27.386500170 +0000
             @@ -1 +1,11 @@
             +# This file was generated by Chef
             +# Do NOT modify this file by hand.
             +
             +[grafana]
             +name=Grafana Stable Repo
             +baseurl=https://packagecloud.io/grafana/stable/el/$releasever/$basearch
             +enabled=1
             +fastestmirror_enabled=0
             +gpgcheck=1
             +gpgkey=https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
             - change mode from '' to '0644'
             - restore selinux security context
           * execute[yum clean metadata grafana] action run
             - execute yum clean metadata --disablerepo=* --enablerepo=grafana
           * execute[yum-makecache-grafana] action run
             - execute yum -q -y makecache --disablerepo=* --enablerepo=grafana
           * ruby_block[package-cache-reload-grafana] action create
             - execute the ruby block package-cache-reload-grafana
           * execute[yum clean metadata grafana] action nothing (skipped due to action :nothing)
           * execute[yum-makecache-grafana] action nothing (skipped due to action :nothing)
           * ruby_block[package-cache-reload-grafana] action nothing (skipped due to action :nothing)
         
         * yum_package[grafana] action install
           - install version 4.6.3-1 of package grafana
```
</summary>

**Comment by mcaulifn** [comment]
@eheydrick any updates?

**Comment by josephholsten** [comment]
@mcaulifn I'm not sure I'm understanding you correctly. Are you setting the attribute in another cookbook? If that's the case, that's very likely going to fail as it depends on cookbook load order for attribute precedence.

The long-term solution to this is for us to stop having this be a recipe- & attribute- oriented implementation and instead use a resource-implementation.

The least terrible work-around would probably be to assign to `default['grafana']['package']['version']` at a higher level of precedence than default.

**Comment by mcaulifn** [comment]
@josephholsten I'm attempting to set the version and install type in the attributes of my wrapper cookbook using the two attributes I showed above. This usually works for other wrapper cookbooks so I'm a bit confused with this one.

Would it work if i set it to `normal` in my attributes file?

**Comment by xorima** [comment]
It should work if you set it to normal @mcaulifn but I am more concerned as to why this isn't working, will try to take a look later today, 

Also we have just released a new version which has the updated grafana version number, so this may be an easy workaround until I have had time to get this working?

**Comment by xorima** [comment]
@mcaulifn I have tried to recreate your issue but have been unable, for reference I have uploaded my test cookbook here: https://github.com/Xorima/test-cookbook

Can I confirm this is exactly what you are doing?

* Create a wrapper cookbook (In my case `test`)
* add to default recipe: `include_recipe 'grafana::default'`
* add to attributes: 
  * `default['grafana']['version'] = '5.2.0'`
  *  `default['grafana']['file']['checksum']['rpm'] = '0f0b7deb4c043c034307067a35248c72888bca7ff45e0f325bb5642825649bfc'`
* converge the `test::default` recipe

**Comment by mcaulifn** [comment]
I created a test cookbook here: https://github.com/mcaulifn/test-cookbook

- Setting the install type to `package`
- Setting the version to `5.2.4`

Otherwise, its the same.

I'm getting this on the test kitchen instance:
```
[vagrant@default-centos-7 ~]$ rpm -qa grafana
grafana-5.3.4-1.x86_64
```

**Comment by xorima** [comment]
I need to do some additional testing but it appears package mode will try to install the version specified from the repository, need to see if 5.2.4 is the version in the apt repo or if it is some other named version

**Comment by xorima** [comment]
Ok so I have found the full source of this issue @mcaulifn 

in the Grafana attributes we are setting a default on `default['grafana']['package']['version'] = "#{node['grafana']['version']}-1"` however this appears to be being processed before your new attributes take effect 

The best way to handle this would be to set this value yourself for now, as I am currently in the process of removing all the recipes out of this cookbook for a 4.0.0 release and we will be using resources going forward

That said if you need me to push in a patch version which will resolve this do let me know? 

Thanks for reporting this, 

Xorima.

**Comment by mcaulifn** [comment]
looks like it has been updated to v4 while i was out. i'll test that one out next. thank you @Xorima !

**Comment by xorima** [comment]
It's still in beta, not a full release yet, will let you know when it is good

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
