### ISSUE TITLE
datasource not updated when declaration changes

### ISSUE THREAD

**Issue by kitchen** [sous-chefs/grafana#204]
### Cookbook version

v2.1.1

### Chef-client version
12.11.18 (Yes, I'm aware this is very old. I'm working on it ;-) )

### Platform Details
Ubuntu 16.04 AWS

### Scenario:
I have a `grafana_datasource` declared in a recipe. I want to change some parameters, but they aren't changing when I run chef:

Old declaration:
```
grafana_datasource 'graphite' do
  datasource(
    type: 'graphite',
    url: 'https://metrics.org.url/graphite',
    access: 'direct',
    isdefault: true,
    organization: 'Cozy'
  )
end

```

New declaration:
```
grafana_datasource 'graphite' do
  datasource(
    type: 'graphite',
    url: 'http://metrics.int.org.url/graphite', # note the url change
    access: 'proxy', # note the change from direct to proxy
    isdefault: true,
    organization: 'Cozy'
  )
end

```

I suspect if I am starting from scratch it works just fine, but it's not changing the existing resource. I think if I change the action to `:update` it will work, but that's not how I expect it to work? I'm fairly new to chef, so perhaps that's an incorrect assumption, and if so, I'm happy to be told otherwise :)

The README suggests a method for updating the resource, but it's not clear to me how that works:

> You can update an existing datasource as follows: `ruby grafana_datasource 'influxdb-test' do datasource( type: 'influxdb_09', url: 'http://10.0.0.10:8086', access: 'proxy', database: 'metrics', user: 'dashboard', password: 'dashpass', isdefault: true ) action :create end`

(sorry, I can't seem to link to a specific line in a markdown file like I would in any other source file, and there's been an issue open for 3 years asking for it 🤣 )

Where would I run that? I have a feeling if I try to run that in any old place ruby is going to tell me it can't find "grafana_datasource" no such file or directory :)

I'll look into how to make chef decide it needs to update the resource as well and hopefully get a PR to you at some point :)

**Comment by kitchen** [comment]
Aha! So, the issue I'm having with the README is actually that the supermarket isn't properly rendering the code block, but if I look at it on github, it is properly rendered. So it appears to me that what I'm trying to do is something that *should* be supported, but isn't working?

https://github.com/sous-chefs/grafana/tree/e98320e82ebfcd87e7aec150d507386765d16449#examples is the documentation saying it should work. But looking at the code, https://github.com/sous-chefs/grafana/blob/e98320e82ebfcd87e7aec150d507386765d16449/providers/datasource.rb#L30-L34 it looks as though the create action simply ignores the resource if it already exists, regardless of its state?

Am I reading this correctly or am I just misunderstanding what's happening under the hood and doing something else wrong? :)

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
