### ISSUE TITLE
Grafana deb & rpm repos have moved

### ISSUE THREAD

**Issue by hrak** [sous-chefs/grafana#220]
### Cookbook version
3.0.1

### Chef-client version
14.4.18

### Platform Details
Ubuntu

The [Grafana repositories have moved](https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/) and the packagecloud.io repos have been discontinued as of 7 Jan 2019.

I can file a PR for it if you wish, but i'm not sure how close to release the current master branch is. If that is not close to release yet i can file PR's against master and against v3.0.1 so you have the option of releasing a v3.0.2 in the meantime.

**Comment by xorima** [comment]
Hi @hrak 

Thanks for highlighting this, if you can do a PR on the 4.0.0 codebase, the only thing left to go is to sort out the ldap recipe, which won't take long then we can ship,

Do you need it in a 3.0.2 release? If so we can sort something out I am sure, 

Xorima

**Comment by hrak** [comment]
I don't really need a 3.0.2, i have fixed it for now by overriding the repo, key and distribution attributes.
