### ISSUE TITLE
Add testing to Amazon Linux 2

### ISSUE THREAD

**Issue by xorima** [sous-chefs/grafana#231]
### Cookbook version
master

### Platform Details
Amazon linux 2

### Scenario:
As a user I want this cookbook to work on AmazonLinux 2

### Steps to Reproduce:
Tests do not include it

### Expected Result:
Tests include Amazon Linux 2

### Actual Result:
Tests do not include it

**Comment by thirumoorthir** [comment]
@Xorima  I Amazon linux is based on RHEL so i think this cookbook will work

**Comment by xorima** [comment]
While true we have seen issues before that only happen on amazon linux 2, which is odd, in other cookbooks, and additional tests don't cost us much really

**Comment by mbaitelman** [comment]
Did some testing locally and it looks like it passes seconds later, is there a way to add a wait or similar? 
I copied the control below the existing one and it works after the first one fails.

**Comment by xorima** [comment]
Tests have been added in #365
