### ISSUE TITLE
config.js.erb template does properly quote datasource parameters.

### ISSUE THREAD

**Issue by ghost** [sous-chefs/grafana#24]
The custom pprint() method used in the default template doesn't quote string values so any values in the datasources attribute hash that might contain special characters cause the site to break. I'm not sure if there's any reason not to use the built in JSON generator instead.  This seems to handle string quoting properly and works just fine:

```
    datasources: <%= ::JSON.pretty_generate(@datasources) %>,
```

**Comment by JonathanTron** [comment]
Yes, there is a reason for this.

If you look up at the default attributes for the datasources (cf: https://github.com/JonathanTron/chef-grafana/blob/master/attributes/default.rb#L55-L67)

``` ruby
default['grafana']['datasources'] = {
  'graphite' => {
    'type' => "'graphite'",
    'url'  => 'window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/_graphite"',
    'default' => true
  },
  'elasticsearch' => {
    'type' => "'elasticsearch'",
    'url'  => 'window.location.protocol+"//"+window.location.hostname+":"+window.location.port',
    'index' => "'#{node['grafana']['grafana_index']}'",
    'grafanaDB' => true
  }
}
```

You can see the `url` params are following the pattern: `'window.location.protocol+"//"+window.location.hostname+":"+window.location.port'`

Once render in the `config.js` template via the `pprint` method it will result in:

``` javascript
url: window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/_graphite",
```

By using `JSON.pretty_generate` you loose control over the end result type, everything would be a string.

Does it make sense?
