### ISSUE TITLE
Cookie issues

### ISSUE THREAD

**Issue by atward** [sous-chefs/grafana#248]
### Cookbook version
v4.2.0

### Issue 1: Inconsistent cookie name
config_session resource has this with a default
https://github.com/sous-chefs/grafana/blob/4256b485b20eb16a9a9f64f2db3c666b1e7fde36/resources/config_session.rb#L27
sub-issue: [Documentation](https://github.com/sous-chefs/grafana/blob/6784ad3016312847b262f83a62a5cfcd3b490184/documentation/grafana_config_session.md) for this config_session does not mention cookie_name parameter

config_auth has this with different default. [Documentation](https://github.com/sous-chefs/grafana/blob/f638c6f3fce513bac8148c468825cd3a3a80b10c/documentation/grafana_config_auth.md) matches line below
https://github.com/sous-chefs/grafana/blob/f638c6f3fce513bac8148c468825cd3a3a80b10c/resources/config_auth.rb#L23

Aside: From Grafana v6.2 [session] has been deprecated.

### Issue 2: API helper hardcodes cookie name
The login helper regex expects `grafana_sess`
https://github.com/sous-chefs/grafana/blob/13b80eb5c461f831148073f85fa3faa54911c62c/libraries/api_helper.rb#L32

### Example Scenario
Using config_auth with default causes resources using API (eg: user, datasouce, dashboard) to fail
```
grafana_config_auth 'grafana'

grafana_datasource 'prometheus' do
  datasource(
    type: 'prometheus',
    url: 'http://localhost:9090',
    access: 'direct'
  )
end
```

### Result:
do_request -> login -> handle_request (Net::HTTPUnauthorized)  
```
ERROR: Invalid grafana_user and grafana_sess.
```

### Expected Result
1. Defaults should be consistent
1. api_helper should honour cookie settings provided

**Comment by atward** [comment]
If there's a nice way to get (or save) property values from a `grafana_config_*` resource I can solve this and #247

**Comment by xorima** [comment]
So currently we do not store those variables anywhere accessible, but we could potentially put them in the node runstate as well, which would make them accessible without being directly saved to the chef server, what are your thoughts on this @atward?

**Comment by atward** [comment]
re issue 1: It should be consistent throughout the cookbook. PR has been raised for that.

re issue 2: At a minimum it should be documented that it expects grafana to return sessions as `grafana_sess`. Users with advanced setups (requiring a specific auth and cookies) could revisit this issue in the future and have the library match inspect the config.
