### ISSUE TITLE
Elasticsearch grafana index is not easily configurable

### ISSUE THREAD

**Issue by sonnysideup** [sous-chefs/grafana#25]
https://github.com/JonathanTron/chef-grafana/blob/master/attributes/default.rb#L64

Since `node['grafana']['datasources']['elasticsearch']['index']` is a derived value (i.e. string interpolated using another node value), it will not change whenever someone changes `node['grafana']['grafana_index']`.

**Comment by JonathanTron** [comment]
I know, this is a pet peave I have with attributes, what do you propose to fix it? 

There's a lot of alternatives, but each have it's own set of problems. 

I'm usually keen to create wrapper cookbooks and `chef-grafana` is meant to be used wrapped into one when default configuration is not enough. Then replacing the whole `default['grafana']['datasources']` makes more sense.

**Comment by sonnysideup** [comment]
You're right, there are a number of alternatives. Let me fork and toy with it a bit to see if can come up with something that works well.
