### ISSUE TITLE
API resources converge prior to service being configured

### ISSUE THREAD

**Issue by atward** [sous-chefs/grafana#257]
### Cookbook version
v4.3.0

### Chef-client version
14.12.9

### Scenario:
The grafana configuration template and service are delayed until the end of the converge. This causes API resources to fail as they're converged prior to the service being correctly configured.

### Steps to Reproduce:
The first run of a recipe which reconfigures grafana and then attempts adds an API resource. From proxy test suite:
```
auth_header = 'X-Example-Header'

grafana_install 'grafana'

grafana_config 'Grafana'

grafana_config_auth 'Grafana' do
  disable_login_form true
  proxy_enabled true
  proxy_header_name auth_header
  proxy_header_property 'username'
  proxy_whitelist '127.0.0.1, ::1'
  login_cookie_name 'grafana_sess'
end

grafana_user 'j.smith' do
  auth_proxy_header auth_header
  user(
    name: 'John Smith',
    email: 'test@example.com',
    password: 'test123',
    isAdmin: true,
    organizations: [
      { name: 'Main Org.', role: 'Admin' },
    ]
  )
  action %i(create update)
end
```
Subsequent converges may succeed

### Expected Result:
User created. Rough order:

* install
* configure
* start service
* configure API resource

### Actual Result:
`grafana_user[j.smith]` converges prior to `template[/etc/grafana/grafana.ini]`

### Discuss
Opening more to discuss a suitable solution. This is somewhat of a limitation in the api library in that it assumes defaults for a number of things. 

My first inclination was to trigger the template render/service restart in the wrapper cookbook at a suitable time (prior to any api resources, maybe with a flag file) - however the service/template aren't available to the `:root` context. The following workaround actually creates new resources:
```
# Ensure template rendered and used before proceeding
service 'grafana-server'
edit_resource(:template, '/etc/grafana/grafana.ini') do
  notifies :restart, 'service[grafana-server]', :immediate
end
log 'Creating initial grafana config if missing' do
  notifies :create, 'template[/etc/grafana/grafana.ini]', :immediate
end
```

My next thought was that api resources should notify a reconfigure/restart `:before` making api calls.

**Comment by atward** [comment]
Full converge log from #255 

```
Recipe: test::proxy
  * grafana_install[grafana] action install
    * yum_repository[grafana] action create
      * template[/etc/yum.repos.d/grafana.repo] action create
        - create new file /etc/yum.repos.d/grafana.repo
        - update content in file /etc/yum.repos.d/grafana.repo from none to 496a14
        - change mode from '' to '0644'
      * execute[yum clean metadata grafana] action run
        - execute yum clean metadata --disablerepo=* --enablerepo=grafana
      * execute[yum-makecache-grafana] action run
        - execute yum -q -y makecache --disablerepo=* --enablerepo=grafana
      * ruby_block[package-cache-reload-grafana] action create
        - execute the ruby block package-cache-reload-grafana
      * execute[yum clean metadata grafana] action nothing (skipped due to action :nothing)
      * execute[yum-makecache-grafana] action nothing (skipped due to action :nothing)
      * ruby_block[package-cache-reload-grafana] action nothing (skipped due to action :nothing)

    * yum_package[grafana] action install
      - install version 0:6.1.6-1.x86_64 of package grafana

  * grafana_config[Grafana] action install
    * linux_user[grafana] action create (up to date)
    * group[grafana] action create (up to date)
    * directory[/etc/grafana] action create
      - change mode from '0755' to '0750'
      - change owner from 'root' to 'grafana'
      - change group from 'root' to 'grafana'
    * service[grafana-server] action enable
      - enable service service[grafana-server]
    * directory[/usr/share/grafana] action create
      - change mode from '0755' to '0750'
      - change owner from 'root' to 'grafana'
      - change group from 'root' to 'grafana'
    * template[/etc/default/grafana-server] action create
      - create new file /etc/default/grafana-server
      - update content in file /etc/default/grafana-server from none to 1117a9
      - change mode from '' to '0644'
    * service[grafana-server] action restart
      - restart service service[grafana-server]
  * template[/etc/grafana/grafana.ini] action nothing (skipped due to action :nothing)
  * grafana_config_auth[Grafana] action install (up to date)
  * grafana_user[j.smith] action create[2019-05-16T22:15:06+00:00] ERROR: Invalid grafana_user and grafana_sess.

    ================================================================================
    Error executing action `create` on resource 'grafana_user[j.smith]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `each' for nil:NilClass

    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/grafana/resources/user.rb:52:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/test/recipes/proxy.rb

     16: grafana_user 'j.smith' do
     17:   auth_proxy_header auth_header
     18:   user(
     19:     name: 'John Smith',
     20:     email: 'test@example.com',
     21:     password: 'test123',
     22:     isAdmin: true,
     23:     organizations: [
     24:       { name: 'Main Org.', role: 'Admin' },
     25:     ]
     26:   )
     27:   action %i(create update)
     28: end

    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/test/recipes/proxy.rb:16:in `from_file'

    grafana_user("j.smith") do
      action [:create, :update]
      default_guard_interpreter :default
      declared_type :grafana_user
      cookbook_name "test"
      recipe_name "proxy"
      auth_proxy_header "X-WEBAUTH-USER"
      user {:name=>"John Smith", :email=>"test@example.com", :password=>"test123", :isAdmin=>true, :organizations=>[{:name=>"Main Org.", :role=>"Admin"}]}
    end

    System Info:
    ------------
    chef_version=15.0.300
    platform=centos
    platform_version=7.6.1810
    ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
    program_name=/opt/chef/embedded/bin/chef-client
    executable=/opt/chef/embedded/bin/chef-client

  * template[/etc/grafana/grafana.ini] action create
    - update content in file /etc/grafana/grafana.ini from 226050 to 14485e
```

Order:
* grafana install
  * default config
  * restart service
* grafana_user
* template[/etc/grafana/grafana.ini]
  * (no restart on config change)

**Comment by HP41** [comment]
Same, I face this exact issue as well. It takes 3 runs to finally converge without issue.

I was wondering how best to do this from a cookbook architecture perspective?

With v7.x.x of this cookbook, the service is now defined in the end cookbook level. Maybe that can be leveraged somehow? 
Perhaps some level of notifies or subscribes can help. The only issue here might be when the service is never restarted (same config) but the API resources have a change and therefore might not flow along (I could be mistaken here). 

Or perhaps another resource that just renders the template on demand which can be placed in between the config and api based resources in the end cookbook.

Any other ideas?

**Comment by xorima** [comment]
Hey @HP41 

You have covered the entire reason this bug is not fixed, due to Grafana not supporting a conf.d this becomes really really tricky to achieve, especially because of:

> The only issue here might be when the service is never restarted (same config) but the API resources have a change and therefore might not flow along (I could be mistaken here).

If anyone has any ideas which can solve this I would be grateful to hear them, I am thinking of looking inside the resource collection to dynamically assign the subscribe, but that does not feel like a correct fix

**Comment by xorima** [comment]
So with the upcomming release of 8.0.0 this should all work now, we have introduced a new resource called `grafana_config_writer` in order to give control to the user as to when the config is written and the service restarted. It should also allow API calls to work straight after this restart

If there are still issues please do re-open this issue or file a new issue
