### ISSUE TITLE
resource config_database.rb does not allow using a custom database name

### ISSUE THREAD

**Issue by vfstaboy** [sous-chefs/grafana#262]
Unable to use custom database name using config_database resource.

https://github.com/sous-chefs/grafana/blob/master/resources/config_database.rb
Line 55 needs to be updated so it does not default to the default database name.
 variables['grafana']['database']['name'] << new_resource.name.to_s unless new_resource.database_name.nil?

Thank you

**Comment by damacus** [comment]
Hey,
Out of interest, why would we need to have a custom database name here? 

If we/you need it, feel free to drop us a PR. If you get stuck ksnd don't know where to stsrt please feel free to reach out. 

Thanks Dan

**Comment by vfstaboy** [comment]
We use shared database servers here and multiple departments that use grafana thus the need for custom database names (grafana_dba, grafana_ops...).  I'll try the PR route thanks.

-George

**Comment by damacus** [comment]
Ah! Interesting. Yeah go for it., shout if you need anything. Don't hesitate to open a draft PR for feedback even if it isn't finished

**Comment by xorima** [comment]
Ah so I have found the issue here:

```
      variables['grafana']['database']['name'] ||= '' unless new_resource.database_name.nil?
      variables['grafana']['database']['name'] << new_resource.name.to_s unless new_resource.database_name.nil?

```
Note the `new_resource.name.to_s` should be `new_resource.database_name.to_s`

This will need to be fixed, I just need to decide if we should change the default to `Grafana` and not `grafana` to reduce breakages, or ship this as a major release

**Comment by xorima** [comment]
This has now been resolved
