### ISSUE TITLE
config_organization doesn't change name of org.

### ISSUE THREAD

**Issue by lumy** [sous-chefs/grafana#264]
# Brief Description

Can't change organization name

## Cookbook version

4.1.0
## Chef-client version

12.21.26

## Platform Details

Debian x64

## Scenario

I'm trying to update the Main organization with a new name, but even on fresh install it won't change.
```
grafana_organization 'Main Org.' do
  admin_user node['grafana']['admin_user']
  admin_password node['grafana']['admin_password']
  port 80
  organization(
    name: node['grafana']['organization']  
  )
  action :update
end
```

```
  * grafana_organization[NewName] action update (up to date)

```

## Steps to Reproduce

Fresh install:
  - grafana_install
  - grafana_config
  - grafana_config_auth
  - grafana_config_database
  - grafana_config_paths
  - grafana_config_security
  - grafana_config_server
  - grafana_config_users
  - grafana_config_organization 

## Expected Result

That the right name is shown in the webapp: /admin/orgs.

## Actual Result

My organization still has the same name.

**Comment by xorima** [comment]
Possibly resolved by #332 

if you are still having issues please re-open
