### ISSUE TITLE
allow_embedding is not available

### ISSUE THREAD

**Issue by pwilson55** [sous-chefs/grafana#268]
# Brief Description
New security setting allow_embedding is not available

## Cookbook version
4.2.0
0
## Chef-client version
pinned to 14
[Version of chef-client in your environment]

## Platform Details
Centos7

## Scenario
Set allow_embedding to true.  Default is false

## Steps to Reproduce
We need to allow grafana graphs to be used in iframes.  This should work:

grafana_config_security 'grafana' do
  allow_embedding true
end

## Expected Result
This will create allow_embedding set to true under the security section of the grafana.ini file.

## Actual Result
       NoMethodError
       -------------
       undefined method `allow_embedding' for Custom resource grafana_config_security from cookbook grafana

**Comment by pwilson55** [comment]
Hello, does anyone but me care about this?  I'm not a developer but I tried to code this and merge it in but I don't know how to handle little issues with my merge.  Could someone please assist ?

**Comment by xorima** [comment]
Hey @pwilson55 do you have a link to the documentation for this option so I can get it added to the cookbook?

**Comment by xorima** [comment]
hi @pwilson55 This has been included in the 5.0.0 release
