### ISSUE TITLE
datasources attributes not overriden

### ISSUE THREAD

**Issue by agonzalezandino** [sous-chefs/grafana#27]
Hello!

First of all, thanks for your great cookbook. It almost covers all that we need for our monitoring platform. Unfortunately there's just one point that we can't resolve: datasources attributes aren't overriden by our custom ones.

Let me explain it in detail: we don't plan to use graphite+elasticsearch. Instead, we'll use influxdb. No problem, let's override the default attributes in the role:

```
    "grafana": {
      "datasources": {
        "'eu-metrics'": {
          "'type'": "'influxdb'",
          "'url'": "'http://our_influxdb_server:8086/db/data_db'",
          "'username'": "'user'",
          "'password'": "'pass'"
        },
        "'grafana'": {
          "'type'": "'influxdb'",
          "'url'": "'http://our_influxdb_server:8086/db/grafana'",
          "'username'": "'test'",
          "'password'": "'test'",
          "'grafanaDB'": true
        }
      }
    }
```

We should expect the graphite+elasticsearch data overriden by the above details. However, what we get is both of them in the config.js file: influxdb is somehow added to the default attributes listed in the default.rb file:

```
// datasources, you can add multiple
    datasources: {
      graphite: {
        type: 'graphite',
        url: window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/_graphite",
        default: true
      },
      elasticsearch: {
        type: 'elasticsearch',
        url: window.location.protocol+"//"+window.location.hostname+":"+window.location.port,
        index: 'grafana-index',
        grafanaDB: true
      },
      'eu-metrics': {
        'type': 'influxdb',
        'url': 'http://our_influxdb_server:8086/db/data_db',
        'username': 'user',
        'password': 'pass'
      },
      'grafana': {
        'type': 'influxdb',
        'url': 'http://our_influxdb_server:8086/db/grafana',
        'username': 'test',
        'password': 'test',
        'grafanaDB': true
      }
    },
```

In order to discard any precedence order, we've also tried to define our custom attributes in the role "override_attributes" field, without result.

Can you please clarify how to use the datasource attribute in order to get this goal?

Thanks in advance!
Andrés

**Comment by JonathanTron** [comment]
Hello,
it comes from the way chef is deep merging attributes hash (see: https://docs.getchef.com/essentials_node_object_deep_merge.html).

Usually I use wrapper cookbooks and reassign the full attribute using

``` ruby
node.override["grafana"]["datasources"] = {
  "newkey" => {}
}
```

But I get that this is a problem when using only attributes from role. Maybe skipping config generation when value is `nil` in `datasources` would be enough to clear defaults, then doing:

``` json
"grafana": {
  "datasources": {
     "graphite": null,
     "elasticsearch": null,
     ... the rest of your config ...
  }
}
```

Would result in config not including `graphite` nor `elasticsearch`. Would this be enough for you?

**Comment by agonzalezandino** [comment]
Hi Jonathan!

Unfortunately skipping config generation by passing "null" values throught the role didn't produce the expected result and 'graphite' along with 'elasticsearch' configuration are still present. I guess the best option is to write a wrapper cookbook as you suggested and start from scratch with the datasources attribute. I'll try that and let you know if I get a positive result.

Thank you!
Andrés

**Comment by JonathanTron** [comment]
Oh I'm sorry, my answer was not clear. I asked if it would solve your problem **if I implement it this way** it's not working like this currently, as you discovered.

**Comment by agonzalezandino** [comment]
Well, actually that would help a lot!

If you finally implement that way to make things work with role attributes, I'd suggest including this relevant information in the README file.

Thank you!
Andrés

**Comment by JonathanTron** [comment]
Please try it and let me know if it works for you.

**Comment by agonzalezandino** [comment]
Hi Jonathan.

I'm afraid it's not working: I've tried to put the 'null' config in both default and override role attributes but I get the same result: graphite and elasticsearch get back to the stage in config.js. As an example in the "override_attributes" role section:

```
  "override_attributes": {
    "grafana": {
      "datasources": {
        "graphite": null,
        "elasticsearch": null,
        <my custom configuration>
```

Kind regards,
Andrés

**Comment by JonathanTron** [comment]
@agonzalezandino after more testing, it's indeed impossible to **delete** a key in an attribute hash via roles. You best option is to do it in a wrapper cookbook.

Thanks for your help on the issue.

**Comment by agonzalezandino** [comment]
No problem! I'll use a wrapper book as you first suggested.

Thank you!
