### ISSUE TITLE
Too many restarts in grafana resources causes the chef run to fail.

### ISSUE THREAD

**Issue by fortman** [sous-chefs/grafana#284]
## :ghost: Brief Description

Systemd only allows so many restarts within a timeframe (default of 6 restarts in 10s).  On first runs, so many sous-chefs resource are referenced in my recipe, that the limit is exceeded.  I also wanted to do restarts on my own chef template file for the [provision datasource file](https://grafana.com/docs/administration/provisioning/#datasources).  

I provide a workaround at the bottom of this text field

## :pancakes: Cookbook version

depends 'grafana', '~> 5.1.1'

## :woman_cook:  Chef-Infra Version

:>chef --version
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3

## :tophat: Platform details

Ubuntu 18.04 in local kitchen virtualbox/vagrant instance

## Steps To Reproduce

Restart grafana more than the Systemd limit

## :police_car: Expected behavior

Want to not blow up my chef run.  Honestly there should only be one or 2 restarts instead of a whole bunch

## :heavy_plus_sign: Additional context

So here is my chef kitchen output from multiple runs.  The first run I have a bunch of plugins I'm installing, and I do this by iterating over a list
```
# Install grafana plugins
node['pgrafana']['plugins'].each do |plugin|
  grafana_plugin plugin do
    action :install
  end
end
```

Here are 2 outputs, one with my plugins which passes the restart limit, the 2nd without the plugins that executes just fine
```
With plugins and fails chef run
:>kitchen destroy && kitchen converge > converge.log 2>&1
:>cat converge.log | grep grafana-server | grep restart
           * service[grafana-server] action restart
             - restart service service[grafana-server]
           * service[grafana-server] action restart
             - restart service service[grafana-server]
           * service[grafana-server] action restart
             - restart service service[grafana-server]
           * service[grafana-server] action restart
             - restart service service[grafana-server]
         * service[grafana-server] action restart
           - restart service service[grafana-server]
         * service[grafana-server] action restart
           - restart service service[grafana-server]
         * service[grafana-server] action restart
           Error executing action `restart` on resource 'service[grafana-server]'
           ---- Begin output of /bin/systemctl --system restart grafana-server ----
           ---- End output of /bin/systemctl --system restart grafana-server ----
           Ran /bin/systemctl --system restart grafana-server returned 1
       ---- Begin output of /bin/systemctl --system restart grafana-server ----
       ---- End output of /bin/systemctl --system restart grafana-server ----
       Ran /bin/systemctl --system restart grafana-server returned 1
```

```
WITHOUT plugins and executes fine
:>kitchen destroy && kitchen converge > converge.log 2>&1
:>cat converge.log | grep grafana-server | grep restart
           * service[grafana-server] action restart
             - restart service service[grafana-server]
         * service[grafana-server] action restart
           - restart service service[grafana-server]
         * service[grafana-server] action restart
           - restart service service[grafana-server]
         * service[grafana-server] action restart
           - restart service service[grafana-server]
```

This isn't just about the plugins, it was just an easy way for me to reduce the number of restarts.  There seems to be a restart with each plugin installed

journalctl output of failed run, where you can see there are too may restarts
```
Sep 25 21:53:17 grafana-ubuntu-1804 grafana-server[16671]: t=2019-09-25T21:53:17+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=Thanos
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: Stopping Grafana instance...
Sep 25 21:53:17 grafana-ubuntu-1804 grafana-server[16671]: t=2019-09-25T21:53:17+0000 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
Sep 25 21:53:17 grafana-ubuntu-1804 grafana-server[16671]: t=2019-09-25T21:53:17+0000 lvl=eror msg="Server shutdown" logger=server reason=nil
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: Stopped Grafana instance.
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: grafana-server.service: Start request repeated too quickly.
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Sep 25 21:53:17 grafana-ubuntu-1804 systemd[1]: Failed to start Grafana instance.
```

Possible workaround.  Doing a quick google search, it appears there are systemd file settings that control the restart behavior.  These are not exposed by this cookbooks grafana config resource, but adding these as options would help.   Possible systemd options: StartLimitIntervalSec and StartLimitBurst

**Comment by xorima** [comment]
Based on the changes in #296 this should not happen anymore,

however if you do want to extend the systemd implementation please create a pull request, as currently we do not own the systemd configuration I would like to keep it that way, so creating a `grafana-server.service.d` and setting the relevant keys under there would seem a better solution.

**Comment by fortman** [comment]
Would it be possible to add a property to the resources that controls whether the resources restart, and just default it to true?  That way the end user can control the behavior on resource call?

**Comment by xorima** [comment]
have you seen the upcoming changes in master, these should reduce restarts heavily

**Comment by fortman** [comment]
Oh, I did not look at that!  Thank you, it looks great :)

**Comment by xorima** [comment]
It should get released in next couple of days, just checking for any other easy breaking changes to bundle

**Comment by xorima** [comment]
v7.0.0 released, closing issue, please re-open if this is still a problem (It will auto lock in 30 days, so if that has happened just create a new issue referencing this issue please)
