### ISSUE TITLE
Delayed attribute interpolation

### ISSUE THREAD

**Issue by obazoud** [sous-chefs/grafana#29]
Hi,

I try to update Grafana to 1.9.0 but its seems that we have evaluation attributes problems.
If I only change 'version' and 'checksum' attribut, url is not modified on Chef server (with 1.8.1).

Maybe we can try [Delayed Interpolation](https://coderanger.net/derived-attributes/).

Thanks.

**Comment by JonathanTron** [comment]
This is a great idea. Would you like to make a PR for this?
