### ISSUE TITLE
Grafana changed default session cookie name

### ISSUE THREAD

**Issue by fortman** [sous-chefs/grafana#329]
## :ghost: Brief Description
Please see 
https://grafana.com/docs/grafana/latest/auth/overview/
The default cookie name now shows `login_cookie_name = grafana_session`.  This cookbook has `grafana_sess` hardcoded all over the place.

## :pancakes: Cookbook version
8.3.0, which is the latest at this moment

## :woman_cook:  Chef-Infra Version
```
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3
```

## :tophat: Platform details
Macos with kitchen in VirtualBox

## Steps To Reproduce

1. Use latest version of Grafana, try to use any resource or library call over the api that requires username/password.
2. It will fail.

## :police_car: Expected behavior
Not to hardcode the session cookie name everywhere

## :heavy_plus_sign: Additional context
I replaced all of the names in https://github.com/sous-chefs/grafana/blob/master/libraries/api_helper.rb
from `grafana_sess` to `grafana_session`, and my grafana_dashboard resources started working.

**Comment by xorima** [comment]
Hey,

Thanks for highlighting this, do you fancy dropping a pr in to fix this?

Thanks!

**Comment by fortman** [comment]
> Hey,
> 
> Thanks for highlighting this, do you fancy dropping a pr in to fix this?
> 
> Thanks!

I can try.  The issue is, I don't think it is a simple search and replace.  The config allows for variable session cookie names, so how to reference variable names in the library files?  Not sure, I'll have to think about it

**Comment by xorima** [comment]
I would store the variable in the node.run_state and then reference that everywhere so you can be sure everything is on the same page, 

if you are stuck or want help pop by the #sous-chef channel on the Chef community Slack https://community-slack.chef.io/

**Comment by mcapra** [comment]
Also running into this. Only lost a tiny bit of time digging into the code before checking issues ;)

This works as a short-term fix:
```ruby
grafana_config_auth 'grafana' do
  login_cookie_name 'grafana_sess'
end

grafana_config_writer 'grafana'
```

I have a fix that uses `node.run_state`, but it needs a bit of cleanup since a few of the API resources don't previously reference an `instance_name` -- `grafana_user` isn't the only affected resource here. I can PR tomorrow if someone hasn't got to it by then.

**Comment by mcapra** [comment]
Also running into this. Only lost a tiny bit of time digging into the code before checking issues ;)

This works as a short-term fix:
```ruby
grafana_config_auth 'grafana' do
  login_cookie_name 'grafana_sess'
end

grafana_config_writer 'grafana'
```

I have a more permanent fix to the "hard-coding" problem that assumes you're leveraging a `grafana_config_auth` to specifically set the `login_cookie_name` and a `grafana_config_writer` to make sure it's written. Unfortunately that's not very resilient to changes to default values. Additionally it introduces a `instance_name` to resources that didn't previously need it.

**Comment by mcapra** [comment]
How about something like this?
https://github.com/mcapra/grafana/commit/ffcca2733cd9e32b6ac0cfbebba7b61ce319674f

`(\w+)=([a-f0-9]{16,32});` would be backwards compatible with the old shorter session IDs if you're into that sort of thing:
https://github.com/grafana/grafana/issues/10652


I think it's reasonably safe to assume the session identifier is the only md5 flavored thing passed in the cookie. This isn't resilient to totally garbage naming conventions in people's config I guess -- could set the directive to something that doesn't match `\w+`. An alternative would be to assume the first value passed is always the session identifier key-value pair -- use a `^` match with md5 flavorings in it or just assume a key-value pair delimited by `;`.

This works in my cookbook. I can put together a PR if we're happy with this.

**Comment by fortman** [comment]
@mcapra I have a PR hope that will fix the issue and supports the backword compatibility issue.

**Comment by xorima** [comment]
@fortman / @mcapra do you know if this issue has now been resolved?

**Comment by xorima** [comment]
Closing as no response, I suspect issue resolved.

If there is still an issue please re-open
