### ISSUE TITLE
Log Configuration not getting updated

### ISSUE THREAD

**Issue by shubhamc183** [sous-chefs/grafana#336]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Hi, I am trying to setup a Grafana on my vagrant box, all the connection to vagrant box is pretty much stable.

I am running this recipe --

```
grafana_config 'grafana' do
    owner 'awesomeUser'
    group 'awesomeUser'
    restart_on_upgrade true
  end
  
  grafana_install 'grafana'
  
  service 'grafana-server' do
    action [:enable, :start]
    subscribes :restart, ['template[/etc/grafana/grafana.ini]', 'template[/etc/grafana/ldap.toml]'], :delayed
  end
  
  grafana_config_log 'grafana' do
    mode 'console file'
    level 'debug'
    file_format 'json'
    file_max_lines 50000
    file_daily_rotate true
    file_max_days 10
  end  
```

Only the awesomeUser is created, Grafana latest version is installed and even the "grafana-server" service is created and it's up, running.

But there is no effect of the logging configuration which I have provided in the last block.

## :pancakes: Cookbook version

8.5.0

## :woman_cook:  Chef-Infra Version

ChefDK version: 4.7.73
Chef Infra Client version: 15.7.32
Chef InSpec version: 4.18.51
Test Kitchen version: 2.3.4
Foodcritic version: 16.2.0
Cookstyle version: 5.20.0

I am using kitchen for local testing!

## :tophat: Platform details

Amazon linux V2: 4.14.104-95.84.amzn2.x86_64

## :police_car: Expected behavior

Expecting the grafana.ini files to change

## :heavy_plus_sign: Additional context

Also, I am little new to using chef so can someone tell what's the difference between using 
grafana_config 'my-grafana'

grafana_config_log 'my-grafana' do
.....
end

Is there any difference in b/w 

grafana_config 'grafana' vs grafana_config 'my-grafana' and later how I use them in any grafana_config_loag/auth/alerting?

**Comment by xorima** [comment]
Hey, can you try this with the config writer resource at the end, https://github.com/sous-chefs/grafana/blob/master/documentation/grafana_config_writer.md

it puts the config on disk

**Comment by shubhamc183** [comment]
Thanks a lot, @Xorima. I missed **grafana_config_writer** and almost wasted a couple of days to debug.

Also, do you want me to create PR where the README.md can specify somewhere about grafana_config_writer to be used in order to write the configuration to the disk?

**Comment by xorima** [comment]
Yes please, clearer documentation is always welcome (as the author of the changes it's too easy for me to forget good docs)

**Comment by shubhamc183** [comment]
@Xorima I have created a PR with small README.md change but it failed. Not sure why I took the from master and trying to merge into the master branch.

**Comment by xorima** [comment]
Merged in, thanks!
