### ISSUE TITLE
Datasources always includes unwanted sources

### ISSUE THREAD

**Issue by begriffs** [sous-chefs/grafana#34]
When I provide a list of the two datasources I would like, the resulting file `/srv/apps/grafana/config.js` contains two extras: `elasticsearch` and `graphite`. How can I get rid of the extra entries?

Here are the recipe attributes I'm using:

``` json
"grafana": {
  "webserver_listen": "*",
  "datasources": {
    "metrics": {
      "type": "'influxdb'",
      "url": "window.location.protocol+'//'+window.location.hostname+':8086/db/metrics'",
      "username": "'foo'",
      "password": "'bar'",
      "default": true
    },
    "grafana": {
      "type": "'influxdb'",
      "url": "window.location.protocol+'//'+window.location.hostname+':8086/db/grafana'",
      "username": "'foo'",
      "password": "'bar'",
      "grafanaDB": true
    }
  }
}
```

I thought the defaults were being merged, so I modified the code to remove defaults, and the keys still end up in the generated config.

``` patch
--- a/attributes/default.rb
+++ b/attributes/default.rb
@@ -52,16 +52,4 @@ default['grafana']['unsaved_changes_warning'] = 'true'
 default['grafana']['playlist_timespan'] = '1m'
 default['grafana']['window_title_prefix'] = 'Grafana - '
 default['grafana']['search_max_results'] = 20
-default['grafana']['datasources'] = {
-  'graphite' => {
-    'type' => "'graphite'",
-    'url'  => 'window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/_graphite"',
-    'default' => true
-  },
-  'elasticsearch' => {
-    'type' => "'elasticsearch'",
-    'url'  => 'window.location.protocol+"//"+window.location.hostname+":"+window.location.port',
-    'index' => lambda { "'#{node['grafana']['grafana_index']}'" },
-    'grafanaDB' => true
-  }
-}
+default['grafana']['datasources'] = { }
```

**Comment by begriffs** [comment]
OK, I discovered if I totally remove `default['grafana']['datasources']` from `attributes/default.rb` then it won't add the unwanted fields.

I also set `es_role` and `graphite_role` to nil, but I'm not sure that has any effect.

**Comment by JonathanTron** [comment]
Hi @begriffs, thanks for reporting the issue.

Chef's attributes can only be merged (when used in `roles` or `attributes` file). 

If you need to delete or replace some key in a nested hash you have to do it in a `recipe`, please see the discussion at https://github.com/JonathanTron/chef-grafana/issues/27.

**Comment by JonathanTron** [comment]
Sorry I closed it by mistake. Please close it yourself if you think it can be.

**Comment by begriffs** [comment]
I'd suggest not including the default datasources, but adding a note to the readme giving them as examples. Would you like me to send those changes in a pull request?

**Comment by JonathanTron** [comment]
This would be a pretty big change and this cookbook would no more work out of the box.
I'm fine with changing the default, but I would like to keep a way to install the cookbook without further config.

**Comment by begriffs** [comment]
That makes sense. I'm using the cookbook through Packer's chef-solo provisioner which only allows me to alter the attributes as far as I can tell. However this means it's impossible for me to use chef-grafana to create a working grafana install unless I do one of three things
1. Overwrite the generated grafana config later on from a shell script
2. Use a forked version of the cookbook having no datasource defaults
3. (maybe) remove the `default: true` from the graphite datasource so that my own `default: true` source will take precedence.

Option three seems good except, like you said, grafana will not work out of the box without explicit datasource configuration. So maybe option two is best for me -- it keeps my deployment cleaner than option one.

**Comment by JonathanTron** [comment]
A 4th option would be to create a wrapper cookbook (instead of maintaining a fork of this cookbook) and overriding the datasource in a recipe.

**Comment by scopenco** [comment]
I suggest you to add possibility to customize config.js template from wrapper cookbook. It will not break the current functionality but allow to set the template config.

**Comment by JonathanTron** [comment]
That's already possible, using the attributes:

```
node.override['grafana']['config_template'] = 'myconfig.js'
node.override['grafana']['config_cookbook'] = 'my_wrapper'
```

**Comment by scopenco** [comment]
@JonathanTron fine

**Comment by lanyonm** [comment]
Hi @scopenco,
Are there any changes to code or documentation you would like to see before we close this issue?

Thanks!
