### ISSUE TITLE
Resources links missing in README.md 

### ISSUE THREAD

**Issue by shubhamc183** [sous-chefs/grafana#367]
The following 3 resources links are missing from the list of Resources under README.md(https://github.com/sous-chefs/grafana#resources)
1. grafana_config_auth_azuread
2. grafana_config_remote_cache
3. grafana_folder

**Comment by xorima** [comment]
Hey @shubhamc183 

Do you want to issue a pr to get these into the read me?

Thanks
Jason

**Comment by shubhamc183** [comment]
I'll send a PR @Xorima for this.

**Comment by shubhamc183** [comment]
@Xorima I have made a PR: https://github.com/sous-chefs/grafana/pull/368

**Comment by xorima** [comment]
Thanks!
