### ISSUE TITLE
Folder rename is not obvious and can cause some grief

### ISSUE THREAD

**Issue by axelrtgs** [sous-chefs/grafana#372]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

`update_folder = new_folder[:title] != new_resource.name` means if the wrapper cookbook wants to have a better description EX: `folder updated for org y` in the case where the same folder name may span multiple orgs it breaks because the resource is designed to use the name to determine if the folder is being renamed.

There is probably a better way to handle the ability to rename without tying it to the name attribute. The idea I have for a fix is to add a new property called original_title either to the resource properties or inside the folder hash and gracefully handle the rename without throwing exceptions. 

## :pancakes: Cookbook version

All fo them that support folders

## :woman_cook:  Chef-Infra Version

All supported ones

## :tophat: Platform details

All supported ones

## Steps To Reproduce

set the name property to anything other than the folder title

## :police_car: Expected behavior

cookbook converges

## :heavy_plus_sign: Additional context

Currently its throwing an exception that it cannot execute `.key?` when calling this function because `folder` is nil: `new_folder[:id] = get_folder_id(folder)`

**Comment by xorima** [comment]
@damacus @tas50 @ramereth would appreciate your thoughts on this.

How is it handled in terraform as well @axelrtgs as they have a grafana provider and maybe we can copy how they handle it if it makes sense to?

**Comment by ramereth** [comment]
I'm having a hard time following an example of how this gets hit. Can you please provide some sample code you have in your wrapper cookbook so I can replicate it locally?

**Comment by axelrtgs** [comment]
if you do this it works fine
```
grafana_folder folder_org1[:title] do
    folder(folder_org1)
    action :update
end

grafana_folder folder_org2[:title] do
    folder(folder_org2)
    action :update
end
```

but lets say the folder has the same name in both orgs you wouldn't know which org its being deployed to, if you want to have the resource name be more descriptive you could do this so the chef output lets you know what org the folder was for but then that triggers the folder rename code and thus the bug since it can't find a folder for that name and returns nil. I realized dashboards I think has a similar issue.

```
grafana_folder "#{folder_org1[:title]} for org: #{folder_org1[:organization]}" do
    folder(folder_org1)
    action :update
end

grafana_folder "#{folder_org2[:title]} for org: #{folder_org2[:organization]}" do
    folder(folder_org2)
    action :update
end
```
