### ISSUE TITLE
Using grafana config resources to only generate a grafana.ini file by bypassing grafana.service enable

### ISSUE THREAD

**Issue by mattp0** [sous-chefs/grafana#378]
### :speaking_head: Foreword

Hello, I am pretty new to the Chef world and have been learning for the last few weeks.   
This may be a bad approach but I am building a cookbook that uses the grafana cookbook to only generate a grafana.ini file.  
The reason for this is because we are using Chef and the grafana cookbook to configure a docker-compose setup. 

## 😦  Problem Statement

The issue that I am having is when using the config_writer resource, it always calls the grafana service enable. The service in this case does not exist as it is planned to be running in a docker container. There is not a method to bypass the enabling of the grafana service so that only the config can be generated. 

## :grey_question: Possible Solution

A solution I thought could work is adding a new property and placing an ``only_if`` guard inside the service restart block. 
I have made this change in a forked version [here](https://github.com/CyberAngler93/grafana/blob/master/resources/config_writer.rb) 

## :arrow_heading_up: Describe alternatives you've considered

1. I have considered that possibly the cookbook was not intended to be used in this manner. 
2. Do not use the config_writer and explore methods for a custom resource to do this. 

## :heavy_plus_sign: Additional context
Thanks for any insight!

**Comment by Arsh25** [comment]
This is a good use case.  We should be able to use this cookbook to configure the Grafana ini file without having Grafana installed. There is nothing in the docs that says that this cookbook is limited to being used for scenarios where Grafana is installed  on the actual machine and not a container.  Having grafana config resources says you can only make the config files and having a hidden service restart breaks the assumption that the only thing you are doing is setting up a config file.

**Comment by ramereth** [comment]
Released as 9.3.0
