### ISSUE TITLE
Enterprise install?

### ISSUE THREAD

**Issue by tsully193** [sous-chefs/grafana#380]
## Problem Statement

Right now it appears there is no way to install specifically the enterprise version of Grafana over the open source version

## Possible Solution

Add a attribute/property to install the enterprise version

**Comment by xorima** [comment]
Hi,

could we get more information, I have no knowledge of the enterprise product.

Would you also be willing to drop a pr in to support this?

**Comment by tsully193** [comment]
Hey yeah so there is just a different edition of grafana called grafana-enterprise as seen here

https://grafana.com/grafana/download?edition=enterprise

the installed apt repo has the package as well 

`grep ^Package packages.grafana.com_oss_deb_dists_stable_main_binary-amd64_Packages | awk '{print $2}' | sort -u`
`grafana`
`grafana-enterprise`

Yeah I could potentially pull something together to support, but it is worth stating that I'm not sure the current `grafana_config_enterprise` setting is working as I believe only the enterprise version respects it.

**Comment by tsully193** [comment]
Actually looks like there is a different apt repo

https://grafana.com/docs/grafana/latest/installation/debian/#install-from-apt-repository

**Comment by ramereth** [comment]
@tsully193 if you have time to create a PR, we'll totally take a look and see if we can get it merged!

**Comment by Arsh25** [comment]
@tsully193 are you working on this? If not then I could take a a stab at it this weekend. I think I have an idea of how to go about it.

**Comment by tsully193** [comment]
Hey @Arsh25 I'm not actively working on it, so feel free to take a shot. I just implemented a work around of adding the enterprise repo and installing the specific package because I had a tight timetable
