### ISSUE TITLE
Actions for `grafana_config_writer`

### ISSUE THREAD

**Issue by chuhn** [sous-chefs/grafana#391]
`grafana_config_writer` seems to have one action `:install`:
https://github.com/sous-chefs/grafana/blob/142cf728619664cbc96aa6f07357b4aecb426094/resources/config_writer.rb#L12

According to https://github.com/sous-chefs/grafana/blob/master/documentation/grafana_config_writer.md#actions the only action is `:create`.
So there is a mismatch.

Actually I'm a bit clueless about the proper use of `grafana_config_writer`:

The scenario I have in mind would have a default recipe:
```
grafana_config

grafana_config_writer
```

and an optional ldap recipe (with `grafana_config_ldap`, `grafana_config_auth` and `grafana_config_ldap_servers`)

My implementation would be:

```
# default.rb:
grafana_config do
   notifies :install|create|run, 'grafana_config_writer[final config]'
end

grafana_config_writer 'final config' do
  action :nothing
end

# ldap-rb
grafana_config do
   notifies :install|create|run, 'grafana_config_writer[final config]'
end
```

Is `grafana_config_writer` supposed to work like that at all?

**Comment by chuhn** [comment]
Ah, I missed that the name attribute ie. `instance_name` must be identical for all `grafana_…` resources.
That might explain some of my confusion.

I suspect the idea is to be able to configure multiple grafana instances on one host.
Then again `/etc/grafana/grafana.ini` is [hard-coded in `grafana_config_writer`](https://github.com/sous-chefs/grafana/blob/142cf728619664cbc96aa6f07357b4aecb426094/resources/config_writer.rb#L15), so rather more confusion.

**Comment by ramereth** [comment]
@chuhn so is this still an issue or not?

**Comment by chuhn** [comment]
Actually it's multiple issues:
1. the documentation is inconsistent for _grafana_config_writer_ (`s/:create/:install/`)
2. the location of `grafana.ini` and `ldap.toml` is configurable but then again hard-coded
3. Notifications for `grafana_config*` resources are not working at all. This should be documented somewhere.

Why are notifications not working?

`grafana_config_[feature]` sets some variables from its properties but does nothing otherwise.
It also does not compare the desired state to the current state.
Therefore if some properties of `grafana_config_[feature]` are modified, the resource will still be considered  _up to date_ and never notify `grafana_config_writer`. So the changes are never actually applied.

So the only way to split up a generic instance setup into multiple recipes seems to be:
```
grafana_config 'my instance'

include_recipe 'my_wrapper_ccokbook::feature` if node['site']['grafana']['enable_feature']

grafana_config_writer 'my instance'
```

Not very elegant, is it?

**Comment by xorima** [comment]
Hi @chuhn 

I have resolved the issue with the documentation and ensured that grafana.ini and ldap.toml are now fully configurable.

Notifications do not work as this uses an accumulator pattern. We use this so we can break down the config into it's multiple constituent parts, otherwise we could only have 1 resource for an entire config file with 1000s of properties which isn't very elegant.
