### ISSUE TITLE
Log filters misplaced in ldap.toml?

### ISSUE THREAD

**Issue by chuhn** [sous-chefs/grafana#392]
According to the comment [herein](https://github.com/sous-chefs/grafana/blob/142cf728619664cbc96aa6f07357b4aecb426094/templates/ldap.toml.erb#L8-L12) and the [grafana documentation](https://grafana.com/docs/grafana/latest/auth/ldap/#troubleshooting) this setting belongs tp `grafana.ini` ([here](https://github.com/sous-chefs/grafana/blob/142cf728619664cbc96aa6f07357b4aecb426094/templates/grafana.ini.erb#L821)), not `ldap.toml`.

Best

Christopher

**Comment by xorima** [comment]
Do you fancy raising a pr to move it into the right file?
