### ISSUE TITLE
Add unsigned plugins support (allow_loading_unsigned_plugins)

### ISSUE THREAD

**Issue by themaroqa** [sous-chefs/grafana#395]
### Foreword

The request is to add the change to manage one between the plugins section in the configuration file (https://grafana.com/docs/grafana/latest/administration/configuration/#plugins-1) or the adding of the GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS environment variable.

## Problem Statement

I'd like to use this feature but at the moment it is not supported here

## Possible Solution

One of the 2 way I descruibed before. I am working on a fork that should add a resource dedicated to the [plugins] section. But I'd like to hear your thoughts

**Comment by ramereth** [comment]
@themaroqa I'd say make a PR and we can go from there!

**Comment by themaroqa** [comment]
PR merged, I suppose we can close the issue.
