### ISSUE TITLE
Add link to supermarket

### ISSUE THREAD

**Issue by spuder** [sous-chefs/grafana#40]
This looks like a great cookbook. 

Most cookbooks I've found on the super market have a 'View Source' button on the right hand side that links to github. 

Here is an example
https://supermarket.chef.io/cookbooks/elasticsearch

Strangely this cookbook doesn't have that link. 
Is that something to do with the metadata.rb? Is there a way a link could be added to the supermarket?

**Comment by JonathanTron** [comment]
Thanks for reporting it, I've configured the urls so that "View Source" and "View Issues" buttons appears on supermarket.
