### ISSUE TITLE
Update cookbook to use latest grafana source (2.1)

### ISSUE THREAD

**Issue by cleveranecdote** [sous-chefs/grafana#62]
Graphite datasource access via proxy not fixed until 2.1. Have to remove cookbook from grafana 2.x instance.

**Comment by lanyonm** [comment]
Hi @cleveranecdote,
Grafana 2.1 is not released yet (and looks to be ~1 month away). I use Grafana 2.0.2 with a Graphite datasource set to proxy. What's the error you're experiencing?

**Comment by cleveranecdote** [comment]
Hi!

I posted the topic at the grafana google group with the issue details:
https://plus.google.com/100043733922754838158/posts/CD4nVKFqXmK

In a nutshell, my https graphite instance wouldnt connect directly (auth
issues) or via proxy (503).

2.1 magically fixed it for the proxy setting.

**Comment by lanyonm** [comment]
Ah - we're connecting to graphite over http, not https.

The current cookbook should be able to successfully install the 2.1.x Grafana (thanks to a patch from @kamaradclimber) builds by overriding the `['grafana']['version']` attribute. Please let us know if that does not work for you.

**Comment by cleveranecdote** [comment]
Ah, I saw the version attribute but was wary of using it.

Overrode to "latest" and it works. Thanks!

**Comment by lanyonm** [comment]
Awesome!
