### ISSUE TITLE
grafana_dashboard doesn't allow uppercase titles

### ISSUE THREAD

**Issue by runningman84** [sous-chefs/grafana#64]
is there any reason for forbidding uppercase names here?

```
         * grafana_dashboard[MYDASH] action create_if_missing

           ================================================================================
           Error executing action `create_if_missing` on resource 'grafana_dashboard[MYDASH]'
           ================================================================================

           RuntimeError
           ------------
           MYDASH did not match the name (MYDASH) in the json
```

**Comment by lanyonm** [comment]
There are three values we're trying to reconcile:
- dashboard lwrp name
- json filename
- grafana dashboard name (the `:slug` [used for lookup](http://docs.grafana.org/reference/http_api/#get-dashboard))

As I recall, it's not possible to have an uppercase dashboard `:slug` in Grafana. If that's no longer the case in future releases we should be able to alleviate this limitation. Does that answer your question?

**Comment by runningman84** [comment]
That's ok for me, the error message was just misleading here.

**Comment by lanyonm** [comment]
@JonathanTron,
What do you think about this change to improve dashboard lwrp error logging: https://github.com/JonathanTron/chef-grafana/compare/master...improve-err-msgs?

**Comment by JonathanTron** [comment]
Seems good to me, if someone have problem understanding what failed from error message we are generating then it's a bug. Thanks to both of you for working it out.
