### ISSUE TITLE
grafana_datasource doesn't update default graphite datasource

### ISSUE THREAD

**Issue by runningman84** [sous-chefs/grafana#65]
If I put this code into my recipe

```
grafana_datasource 'graphite2' do
  port 3015
  source(
    type: 'graphite',
    url: 'http://127.0.0.1:8080',
    access: 'proxy',
    isdefault: true
  )
  action :create
end
```

I get a new datasource called graphite2.

If I change the name to graphite like this

```
grafana_datasource 'graphite' do
  port 3015
  source(
    type: 'graphite',
    url: 'http://127.0.0.1:8080',
    access: 'proxy',
    isdefault: true
  )
  action :create
end
```

each chef run will create or update a datasource with other settings like direct access, notdefault, ...

**Comment by lanyonm** [comment]
Hey @runningman84,
Could you further describe the unexpected behavior you're seeing? The way the lwrp looks up datasources in grafana for modification is by name - so if you change the name as you describe above, it will create a new resource.

**Comment by runningman84** [comment]
The problem is that it is not possible to add a datasource with the name graphite. If you do so none of the settings (like access, isdefault, ...) are used. 

I suppose the problem is caused by an already existing datasource with the name graphite which the lwrp does not modify.

You can just put "grafana_datasource 'graphite2'" and "grafana_datasource 'graphite'" into a recipe. This will create a new datasource graphite2 with the correct settings and will leave the datasource graphite unchanged with wrong settings.

Do you understand?

**Comment by lanyonm** [comment]
I understand, but when testing I have not been able to reproduce those results. I'm testing by adding the following to the default recipe:

``` ruby
grafana_datasource 'graphite' do
  port ['grafana']['ini']['server']['http_port']
  source(
    type: 'graphite',
    url: 'http://graphite.example.com:8080',
    access: 'proxy',
    isdefault: true
  )
  action :create
end
```

And running the following kitchen command:

```
bundle exec kitchen verify default-ubuntu-1404
```

The result is a datasource named "graphite":
<img width="958" alt="grafana-graphite-datasource" src="https://cloud.githubusercontent.com/assets/748947/8728099/41af2904-2bb1-11e5-8436-a16a6d9c6847.png">

I assume you're seeing different results?

**Comment by runningman84** [comment]
Yes, I did see different results. But I found the error I had a wrong cookbook version in my Berksfile. This seems to work now. Thanks for your help!
