### ISSUE TITLE
init script fails during creation of db tables

### ISSUE THREAD

**Issue by lesaux** [sous-chefs/grafana#66]
when using a DB backend, the init script will fail on the first startup of grafana, while grafana is creating tables in the database.
A quick workaround for me was to add "sleep 10" on startup.

**Comment by lanyonm** [comment]
Hi @lesaux,
Do you think this could be related to #61?

Also, I would be interested to know if adding sleeps into the login retries would solve the issue you're seeing: https://github.com/JonathanTron/chef-grafana/blob/master/libraries/api_helper.rb#L19-L21

Additional information about your situation would help us understand the behavior you're seeing.

Thanks!

**Comment by lanyonm** [comment]
Hi @lesaux,
We would appreciate your assistance in defining and reproducing the issue you encountered.

If you found it to be temporal or aren't able to provide further insight, this issues will be closed when we cut the 2.1 release.

Thanks!

**Comment by lesaux** [comment]
Sorry for the delay, I will provide more details later today.

**Comment by lesaux** [comment]
This can be closed. The problem is in the grafana init script itself.
on the first start of grafana, creation of the tables in the DB takes several seconds

This is not taken into account in the init script.
https://github.com/grafana/grafana/blob/master/packaging/deb/init.d/grafana-server 
Adding 'sleep 10' on line 84 permits the init script to execute cleanly on the first start of grafana.
Downside is that all subsequent starts of grafana also sleep for 10seconds for no reason.
I'll mention this on the grafana issues.

Sorry for bringing it here in the first place.

**Comment by lanyonm** [comment]
No worries! Thanks for following up.
