### ISSUE TITLE
Grafana 2.1.1 missing [security] section

### ISSUE THREAD

**Issue by chrisduong** [sous-chefs/grafana#75]
I'm installing Grafana version 2.1.1. When I open the config `grafana.ini` file, there is no [security] section.
We could add them by defining attributes:

``` ruby
default['grafana']['ini']['security']['admin_user'] = 'admin'
default['grafana']['ini']['security']['admin_password'] = 'admin'
```

**Comment by JonathanTron** [comment]
Hi @chrisduong, thanks for reporting this. 

This is something which should be handled when you configure your installation (via a wrapper cookbook, or role attributes, etc.). 

I personally don't like adding fixed login/password like this in the default cookbook, as stated in the readme, the cookbook do not try to handle the security part of running Grafana, but provide everything you need to configure it for security.

Thanks again for asking about it!

**Comment by chrisduong** [comment]
Thanks for the feedback
