### ISSUE TITLE
grafana_datasource resource returning nil error

### ISSUE THREAD

**Issue by domofactor** [sous-chefs/grafana#76]
I'm seeing some weird results when trying to use the grafana_datasource resource. 

The converge finishes, but throws the following nil error and I don't see a datasource in grafana. :\

Any help with this would be greatly appreciated, thanks!

test-kitchen 1.4.2
chef 12.4.1 running chef zero

recipe:

```
include_recipe "grafana::default"

grafana_datasource 'graphite2' do
  port node['grafana']['ini']['server']['http_port']
  source(
    type: 'Graphite',
    url: 'http://127.0.0.1:8080',
    access: 'proxy',
    isdefault: true
  )
  action :create
end

grafana_dashboard 'basic-health' do
  port node['grafana']['ini']['server']['http_port']
  source "basic-health"
  overwrite false
end
```

converge:

```
         * grafana_datasource[graphite2] action create[2015-08-19T02:08:42+00:00] ERROR: nil

           - Creating data source graphite2

       Running handlers:
       Running handlers complete
       Chef Client finished, 3/51 resources updated in 17.68031387 seconds
       Finished converging <grafana-ubuntu-1404> (0m40.85s).
-----> Kitchen is finished. (0m41.37s)
```

**Comment by domofactor** [comment]
Looks like updating to release 2.1 fixed my issue, thanks!

**Comment by JonathanTron** [comment]
Great, I'm adding better debug messages in some cases where we previously would have this kind of unhelpful `Error: nil`.

Thanks for reporting it and following up on it.
