### ISSUE TITLE
ERROR: Endpoint not found when sending GET /api/admin/users

### ISSUE THREAD

**Issue by dthapa** [sous-chefs/grafana#82]
I am trying to add a user as such,

grafana_user 'person2' do
  port grafana_port
  full_name 'John Smith'
  email 'test@example.com'
  passwd 'test123'
  admin false
  action :create_if_missing
end

while processing, get_global_user_list() in libraries/user_api.rb gets called and there is a GET call to /api/admin/users. Peeking into the api docs, I don't see GET allowed for that endpoint, but there is something around api/users.

the following is the error I recieved. please help.

[2015-09-02T03:02:25+00:00] ERROR: Endpoint not found when sending GET /api/admin/users

```
       ================================================================================
       Error executing action `create_if_missing` on resource 'grafana_user[person2]'
       ================================================================================

       TypeError
       ---------
       no implicit conversion of String into Integer

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:27:in `[]'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:27:in `block (2 levels) in class_from_file'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:26:in `each'
       /tmp/kitchen/cache/cookbooks/grafana/providers/user.rb:26:in `block in class_from_file'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/demo-grafana/recipes/default.rb

        32: grafana_user 'person2' do
        33:   port grafana_port
        34:   full_name 'John Smith'
        35:   email 'test@example.com'
        36:   passwd 'test123'
        37:   admin false
        38:   action :create_if_missing
        39: end

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/demo-grafana/recipes/default.rb:32:in `from_file'

       grafana_user("person2") do
         action [:create_if_missing]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :grafana_user
         cookbook_name "demo-grafana"
         recipe_name "default"
         port 8080
         full_name "John Smith"
         email "test@example.com"
         passwd "test123"
         host "localhost"
         user "admin"
         password "admin"
         login "person2"
         global true
       end


   Running handlers:
   [2015-09-02T03:02:25+00:00] ERROR: Running exception handlers
   Running handlers complete
   [2015-09-02T03:02:25+00:00] ERROR: Exception handlers complete
   Chef Client failed. 1 resources updated in 6.669768779 seconds
   [2015-09-02T03:02:25+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   [2015-09-02T03:02:25+00:00] ERROR: grafana_user[person2] (demo-grafana::default line 32) had an error: TypeError: no implicit conversion of String into Integer
   [2015-09-02T03:02:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lanyonm** [comment]
Hi @dthapa,
From the look of the error, I would assume that `grafana_port` is a string instead of an integer. Could you try converting with the `to_i` method? If that doesn't work, please provide some of the recipe code you're using.

Thanks!

**Comment by dthapa** [comment]
thanks for the quick response @lanyonm 
Here is the entirety of the wrapper recipe, I had success with datasource and dashboard

include_recipe "grafana"

data_sources = node['grafana']['data_sources']
grafana_port = Integer(node['grafana']['ini']['server']['http_port'])

data_sources.each do |data_source|
  grafana_datasource data_source.name do
    port grafana_port
    source(
        type: data_source.type,
        url: data_source.url,
        access: 'proxy',
        isdefault: data_source.isDefault
    )
    action :create_if_missing
  end
end

grafana_dashboard 'stage' do
  source 'Stage'
  port grafana_port
end

grafana_user 'person2' do
  port grafana_port
  full_name 'John Smith'
  email 'test@example.com'
  passwd 'test123'
  admin false
  action :create_if_missing
end

**Comment by JonathanTron** [comment]
Hi @dthapa it looks like it's related to issue #81, the error is triggered when we try to use the result of the `get_global_user_list` method in:

https://github.com/JonathanTron/chef-grafana/blob/8577f4fa5f77ddaf817974143d3d766480f80fa2/providers/user.rb#L22-L27

It seems we get an array out of the method this time (in #81 it returned `nil`) but the elements in this array  are not a `Hash` like we're expecting...

You're right that there is no way to get a list of the `Global users` which the `grafana_user` is creating... this seems to have been overlooked and is definitely a bug.

@lanyonm I think we should handle the two different kind of users, `Global` and `Normal`, from a compatibility standpoint I think we should implement it as an extra option in the current `grafana_user` resource. What do you think?

**Comment by JonathanTron** [comment]
After reading more carefully the Grafana docs and code, it looks like it's possible to create `Global user` via a `POST /api/admin/user` but there is not way to create a simple user via the HTTP API, you can list `users` (but I don't if it will return any `global user`) via `GET /api/users`.

This is really cumbersome... I don't know yet what we can do about it, I'll have to dive more in the code to understand how we could handle this. 

In the meantime we should replace the check for the user existence which call an endpoint which don't exists.

**Comment by lanyonm** [comment]
Yeah - the user api was undocumented in the 2.0.x releases and may have changed with the 2.1.x releases. I think we should mark the user LWRP as beta or experimental given the complexity of different user types.

I can fix the identified bugs above and make the error messages more meaningful, but probably won't be able to get to it till late next weekend.
