### ISSUE TITLE
Error create grafana_datasource?

### ISSUE THREAD

**Issue by lcc2207** [sous-chefs/grafana#83]
Any else seeing this error below?  It seems to work on the second run.

rror executing action `create` on resource 'grafana_datasource[graphite]'
           ================================================================================

```
       NoMethodError
       -------------
       undefined method `each' for nil:NilClass

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:31:in `create'
       /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:12:in `block in class_from_file'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/cas_graphite/recipes/grafana.rb

         3: grafana_datasource 'graphite' do
         4:   source(
         5:     type: 'graphite',
         6:     url: "http://#{node['cas_graphite']['graphite']['host']}:#{node['graphite']['port']}",
         7:     access: 'direct'
         8:   )
         9: end
```

**Comment by lanyonm** [comment]
Hi @lcc2207,
It appears this may be related to #81. Could you let us know what version of the cookbook and what version of Grafana you're using?

Thanks!

**Comment by lcc2207** [comment]
depends 'grafana', '~> 2.1.3'

**Comment by lanyonm** [comment]
Thanks. Assuming the issue you've encountered is the same as #81, could you have a look in your Grafana log to see if anything may be preventing the service from starting?

**Comment by lcc2207** [comment]
no errors in the log

**Comment by lcc2207** [comment]
Adding the 20 sleep seemed to solve the issues 

execute 'sleep' do
  command '/bin/sleep 20'
end

**Comment by sterago** [comment]
I had a similar issue and fixed using the `retries` directive:

```
grafana_datasource 'influxdb' do
  retries 10
  source(
      type: 'influxdb',
      [...]
  )
  action :create_if_missing
end
```

since the default value for `retry_delay` is 2 seconds, the worst case is equivalent to the 20 seconds sleep solution by @lcc2207
