### ISSUE TITLE
How to define the admin password?

### ISSUE THREAD

**Issue by diegobill** [sous-chefs/grafana#84]
How to define the admin password?

**Comment by lanyonm** [comment]
Hi @diegobill,
To set the admin password you would use an attribute as follows:

``` ruby
default['grafana']['ini']['security']['admin_password'] = 'your-admin-passwd'
```

Let us know if you have any other questions. Thanks.

**Comment by diegobill** [comment]
Thanks
Em 22/09/2015 11:13, "Michael Lanyon" notifications@github.com escreveu:
