### ISSUE TITLE
dashbord LWRP name attribute fails if not downcase'd

### ISSUE THREAD

**Issue by CVTJNII** [sous-chefs/grafana#85]
The dashboard sanity check throws an error if the LWRP name contains an uppercase character:

https://github.com/JonathanTron/chef-grafana/blob/master/libraries/dashboard_api.rb#L98-L99

This seems overly strict, both the dashboard title and the LWRP name allow uppercase letters.  Is there a reason for this restriction I'm not aware of?

**Comment by lanyonm** [comment]
The Grafana API uses a `slug` to query for a dashboard (http://docs.grafana.org/reference/http_api/#get-dashboard). The slug is supposed to be a "url-friendly" value, hence the restriction.

If I recall correctly the LWRP should allow for mixed case dashboard titles, but the design decision was to have the LWRP name match the slug that Grafana is queried against. The LWRP was written before the Grafana API was documented, so it's possible there's now a cleaner way to do this.

**Comment by lanyonm** [comment]
Closing this for now. Please reopen if you have further questions!

**Comment by gkuchta** [comment]
FWIW, the Grafana API explictly allows mixed-case and spaces in dashboard titles. It seems like it'd make more sense to remove the `#tr` and `#downcase` calls in the sanity check, and just transform the string when posting to the API.
