### ISSUE TITLE
Providers consistency

### ISSUE THREAD

**Issue by jbfavre** [sous-chefs/grafana#90]
Hello,
I'm about to start working on grafana_user provider.
While looking on what is done  currently, I figured out some inconsistencies between providers.

Resources definition sometime use a nemd Hash to pass all variables like `grafana_datasource`:

```
grafana_datasource 'graphite-test' do
  source(
    type: 'graphite',
    url: 'http://10.0.0.15:8080',
    access: 'direct'
  )
end
```

Some other pass variables directly like `grafana_user`:

```
grafana_user 'person2' do
  full_name 'John Smith'
  email 'test@example.com'
  passwd 'test123'
end
```

I would like to make all providers work the first way, but this would result in functional change.

Comments are very welcome :)

Thanks

**Comment by lanyonm** [comment]
Hey @jbfavre,
This proposal looks good to me. #82 related to an API change that was made between Grafana 2.0 and 2.1, so you'll likely run into the same issue as you refactor.

Thanks

**Comment by jbfavre** [comment]
Hey @lanyonm 
Yes, I already faced the #82 issue :)
For now, I'm able to create & delete a user.
I'm also able to update user's details as well as password (and login BTW).
Next step is to manage organizations user belong to. It should be OK this week and I'll make a PR.

**Comment by jbfavre** [comment]
Code is available in branch feat_improve_user_provider on my github chef-grafana fork

What I implemented so far:

Create

```
grafana_user 'j.smith' do
  user(
    name: 'John Smith',
    login: 'j.smith',
    email: 'test@example.com',
    passwd: 'test123'
  )
  action :create_if_missing
end
```

Update:

```
grafana_user 'j.smith' do
  user(
    name: 'John Smith',
    login: 'j.smith',
    email: 'another-test@example.com',
    passwd: 'test1234'
  )
  action :update
end
```

but you can also update login (old login is resource name, new login passed as param):

```
grafana_user 'j.smith' do
  user(
    name: 'John Smith',
    login: 'john.smith',
    email: 'test@example.com',
    passwd: 'test1234'
  )
  action :update
end
```

and of course delete:

```
grafana_user 'john.smith' do
  action :delete
end
```

**Comment by lanyonm** [comment]
Looks good. :+1: 

Is the resource name an altogether different value in grafana that stays the same even if you change the `login`?

**Comment by jbfavre** [comment]
The only need for resource name is to update login.
In other cases, I would recommend setting resource name the same value as login, because login must be unique in Grafana.

**Comment by jbfavre** [comment]
Just pushed an update on my branch:
- Replaced create_if_missing with create (sounds more logic to me)
- By default, use resource name as user's login. **Providing login is not mandatory anymore (except for login update of course)** (I figured out it's not intuitive at all. Even I got screwed with previous behaviour)
